### ISSUE TITLE
[CRASH] 'ckeysExpired == db->expireSize()' is not true, on Active Replication

### ISSUE THREAD

**Issue by solracsf** [Snapchat/KeyDB#428] opened 2022-05-18 13:27 UTC
**Crash report**

Paste the complete crash log between the quotes below. Please include a few lines from the log preceding the crash report to provide some context.

```
=== KEYDB BUG REPORT START: Cut & paste starting from here ===
4111939:4129518:S 18 May 2022 15:21:08.202 # === ASSERTION FAILED ===
4111939:4129518:S 18 May 2022 15:21:08.202 # ==> rdb.cpp:1376 'ckeysExpired == db->expireSize()' is not true

------ STACK TRACE ------

Backtrace:
/usr/bin/keydb-server 127.0.0.1:6379(rdbSaveRio(_rio*, redisDbPersistentDataSnapshot const**, int*, int, rdbSaveInfo*)+0x51d) [0x5602b3331bdd]
/usr/bin/keydb-server 127.0.0.1:6379(rdbSaveFile(char*, redisDbPersistentDataSnapshot const**, rdbSaveInfo*)+0xea) [0x5602b3331cfa]
/usr/bin/keydb-server 127.0.0.1:6379(rdbSave(redisDbPersistentDataSnapshot const**, rdbSaveInfo*)+0x69) [0x5602b3332029]
/usr/bin/keydb-server 127.0.0.1:6379(rdbSaveThread(void*)+0x30f) [0x5602b33378ef]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f1f460ce609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f1f45ff1133]

------ INFO OUTPUT ------
# Server
redis_version:6.3.0
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:bc455d014a017397
redis_mode:standalone
os:Linux 5.4.0-109-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:9.3.0
process_id:4111939
process_supervised:systemd
run_id:ad877fcb161cb43c31ce8d9f81734a7e3228d576
tcp_port:6379
server_time_usec:1652880068198069
uptime_in_seconds:602
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:8712900
executable:/usr/bin/keydb-server
config_file:/etc/keydb/keydb.conf

# Clients
connected_clients:215
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:360
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0
current_client_thread:1735743595
thread_0_clients:108
thread_1_clients:108

# Memory
used_memory:38511784
used_memory_human:36.73M
used_memory_rss:31891456
used_memory_rss_human:30.41M
used_memory_peak:38569200
used_memory_peak_human:36.78M
used_memory_peak_perc:99.85%
used_memory_overhead:16214832
used_memory_startup:10419760
used_memory_dataset:22296952
used_memory_dataset_perc:79.37%
allocator_allocated:18851992
allocator_active:21073920
allocator_resident:27336704
total_system_memory:8144506880
total_system_memory_human:7.59G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:1073741824
maxmemory_human:1.00G
maxmemory_policy:allkeys-lru
allocator_frag_ratio:1.12
allocator_frag_bytes:2221928
allocator_rss_ratio:1.30
allocator_rss_bytes:6262784
rss_overhead_ratio:1.17
rss_overhead_bytes:4554752
mem_fragmentation_ratio:1.79
mem_fragmentation_bytes:14078128
mem_not_counted_for_evict:1048576
mem_replication_backlog:1048576
mem_clients_slaves:20512
mem_clients_normal:4223992
mem_aof_buffer:0
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0
storage_provider:none

# Persistence
loading:0
current_cow_size:34770944
current_cow_size_age:600
current_fork_perc:0.00
current_save_keys_processed:1
current_save_keys_total:0
rdb_changes_since_last_save:4634
rdb_bgsave_in_progress:1
rdb_last_save_time:1652879467
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:0
rdb_last_cow_size:34832384
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:628
total_commands_processed:32723
instantaneous_ops_per_sec:742
total_net_input_bytes:4073064
total_net_output_bytes:4519032
instantaneous_input_kbps:91.21
instantaneous_output_kbps:262.27
rejected_connections:0
sync_full:2
sync_partial_ok:0
sync_partial_err:1
expired_keys:334
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:10156
keyspace_misses:3297
pubsub_channels:11
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:26570
total_writes_processed:32693
instantaneous_lock_contention:0
avg_lock_contention:0.203125
storage_provider_read_hits:0
storage_provider_read_misses:0

# Replication
role:active-replica
master_global_link_status:down
connected_masters:0
master_host:10.1.0.3
master_port:6379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:0
slave_read_repl_offset:2168278
slave_repl_offset:2168278
master_link_down_since_seconds:1
slave_priority:100
slave_read_only:0
replica_announced:1
connected_slaves:1
slave0:ip=10.1.0.3,port=6379,state=wait_bgsave,offset=0,lag=0
master_failover_state:no-failover
master_replid:5ee7555c20391d1be81921a4fc235548d0766dff
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:1799392
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:750817
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:5.855103
used_cpu_user:8.091830
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
server_threads:2
long_lock_waits:2
used_cpu_sys_main_thread:0.000000
used_cpu_user_main_thread:0.012034

# Modules

# Commandstats
cmdstat_psync:calls=2,usec=29419,usec_per_call=14709.50,rejected_calls=0,failed_calls=0
cmdstat_set:calls=2074,usec=20492,usec_per_call=9.88,rejected_calls=0,failed_calls=0
cmdstat_watch:calls=89,usec=238,usec_per_call=2.67,rejected_calls=0,failed_calls=0
cmdstat_echo:calls=1844,usec=5421,usec_per_call=2.94,rejected_calls=0,failed_calls=0
cmdstat_pexpireat:calls=219,usec=1567,usec_per_call=7.16,rejected_calls=0,failed_calls=0
cmdstat_multi:calls=193,usec=141,usec_per_call=0.73,rejected_calls=0,failed_calls=0
cmdstat_expire:calls=95,usec=533,usec_per_call=5.61,rejected_calls=0,failed_calls=0
cmdstat_replping:calls=2,usec=3,usec_per_call=1.50,rejected_calls=0,failed_calls=0
cmdstat_incrby:calls=263,usec=2013,usec_per_call=7.65,rejected_calls=0,failed_calls=0
cmdstat_decrby:calls=62,usec=511,usec_per_call=8.24,rejected_calls=0,failed_calls=0
cmdstat_get:calls=12515,usec=100004,usec_per_call=7.99,rejected_calls=0,failed_calls=0
cmdstat_unwatch:calls=22,usec=67,usec_per_call=3.05,rejected_calls=0,failed_calls=0
cmdstat_KEYDB.MVCCRESTORE:calls=576,usec=1632,usec_per_call=2.83,rejected_calls=0,failed_calls=0
cmdstat_exists:calls=1697,usec=5775,usec_per_call=3.40,rejected_calls=0,failed_calls=0
cmdstat_select:calls=2465,usec=5350,usec_per_call=2.17,rejected_calls=0,failed_calls=0
cmdstat_rreplay:calls=7787,usec=105476,usec_per_call=13.55,rejected_calls=0,failed_calls=0
cmdstat_setex:calls=1137,usec=17234,usec_per_call=15.16,rejected_calls=0,failed_calls=0
cmdstat_del:calls=169,usec=1209,usec_per_call=7.15,rejected_calls=0,failed_calls=0
cmdstat_subscribe:calls=187,usec=920,usec_per_call=4.92,rejected_calls=0,failed_calls=0
cmdstat_exec:calls=193,usec=2845,usec_per_call=14.74,rejected_calls=0,failed_calls=0
cmdstat_replconf:calls=601,usec=1249,usec_per_call=2.08,rejected_calls=0,failed_calls=0
cmdstat_publish:calls=472,usec=10652,usec_per_call=22.57,rejected_calls=0,failed_calls=0
cmdstat_ping:calls=59,usec=43,usec_per_call=0.73,rejected_calls=0,failed_calls=0

# Errorstats

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=71,expires=65,avg_ttl=8390370178780633088,cached_keys=71
db1:keys=14,expires=14,avg_ttl=7625909362398592000,cached_keys=14
db2:keys=241,expires=180,avg_ttl=43798964773871976,cached_keys=241
db3:keys=11,expires=0,avg_ttl=0,cached_keys=11
db4:keys=56,expires=51,avg_ttl=3439822868195400192,cached_keys=56
db5:keys=19,expires=0,avg_ttl=0,cached_keys=19
db6:keys=93,expires=73,avg_ttl=12277952439748620,cached_keys=93
db7:keys=19,expires=0,avg_ttl=0,cached_keys=19
db8:keys=634,expires=573,avg_ttl=20705572669190216,cached_keys=634
db9:keys=69,expires=61,avg_ttl=1402508465148768512,cached_keys=69
db10:keys=19,expires=15,avg_ttl=171040,cached_keys=19
db11:keys=58,expires=38,avg_ttl=137730,cached_keys=58
db12:keys=40,expires=36,avg_ttl=508864,cached_keys=40
db13:keys=24,expires=2,avg_ttl=355779,cached_keys=24
db14:keys=4,expires=0,avg_ttl=0,cached_keys=4
db15:keys=24,expires=0,avg_ttl=0,cached_keys=24
db16:keys=21,expires=17,avg_ttl=3430029413725811712,cached_keys=21
db17:keys=25,expires=19,avg_ttl=3515942792136043520,cached_keys=25
db18:keys=7,expires=7,avg_ttl=723099224529815808,cached_keys=7
db19:keys=70,expires=59,avg_ttl=3968513367523315712,cached_keys=70
db20:keys=93,expires=85,avg_ttl=824537412792734336,cached_keys=93
db21:keys=25,expires=21,avg_ttl=6751038335294198784,cached_keys=25
db22:keys=20,expires=6,avg_ttl=292394,cached_keys=20
db23:keys=15,expires=3,avg_ttl=202586,cached_keys=15
db24:keys=426,expires=381,avg_ttl=2995350098082836,cached_keys=426
db25:keys=26,expires=20,avg_ttl=501913,cached_keys=26
db26:keys=28,expires=23,avg_ttl=2430460415709187584,cached_keys=28
db28:keys=15,expires=0,avg_ttl=0,cached_keys=15
db29:keys=27,expires=5,avg_ttl=180590,cached_keys=27
db30:keys=8,expires=8,avg_ttl=6959879998927706112,cached_keys=8
db31:keys=28,expires=0,avg_ttl=0,cached_keys=28
db32:keys=152,expires=29,avg_ttl=48829607915297352,cached_keys=152
db33:keys=15,expires=3,avg_ttl=62899,cached_keys=15
db34:keys=23,expires=0,avg_ttl=0,cached_keys=23
db35:keys=21,expires=0,avg_ttl=0,cached_keys=21
db36:keys=19,expires=0,avg_ttl=0,cached_keys=19
db37:keys=15,expires=0,avg_ttl=0,cached_keys=15
db38:keys=5,expires=1,avg_ttl=211904,cached_keys=5
db39:keys=24,expires=4,avg_ttl=67102,cached_keys=24

# KeyDB
mvcc_depth:2
```

**Aditional information**

1. Ubuntu 20.04
2. KeyDB v6.3.0

Latest log lines before crash were:

```
4111939:4111948:S 18 May 2022 15:21:07.860 # Connection with replica client id #7 lost.
4111939:4111948:S 18 May 2022 15:21:07.860 # Connection with master lost.
4111939:4111948:S 18 May 2022 15:21:07.860 * Caching the disconnected master state.
4111939:4111949:S 18 May 2022 15:21:08.174 * Replica 10.1.0.3:6379 asks for synchronization
4111939:4111949:S 18 May 2022 15:21:08.174 * Unable to partial resync with replica 10.1.0.3:6379 for lack of backlog (Replica request was: 0).
4111939:4111949:S 18 May 2022 15:21:08.174 * Starting BGSAVE for SYNC with target: disk
4111939:4111949:S 18 May 2022 15:21:08.189 * Background saving started
```

**Comment by solracsf** [comment] 2022-05-18 13:35
The 2nd server also CRASHED with this:

```
1856148:1856158:S 18 May 2022 15:11:06.391 * Non blocking connect for SYNC fired the event.
1856148:1856158:S 18 May 2022 15:11:06.396 * Master replied to PING, replication can continue...
1856148:1856158:S 18 May 2022 15:11:06.402 * Trying a partial resynchronization (request 5ee7555c20391d1be81921a4fc235548d0766dff:11898).
1856148:1856158:S 18 May 2022 15:11:06.424 * Full resync from master: 5ee7555c20391d1be81921a4fc235548d0766dff:1316446
1856148:1856158:S 18 May 2022 15:11:06.424 * Discarding previously cached master state.
1856148:1856158:S 18 May 2022 15:11:06.611 # I/O error reading bulk count from MASTER: Operation now in progress
1856148:1856158:S 18 May 2022 15:11:06.881 * Replica 10.1.0.2:6379 asks for synchronization
1856148:1856158:S 18 May 2022 15:11:06.881 * Unable to partial resync with replica 10.1.0.2:6379 for lack of backlog (Replica request was: 0).
1856148:1856158:S 18 May 2022 15:11:06.881 * Replication backlog created, my new replication IDs are '768b568dc2903056b9ef5051a7a00da32e537135' and '0000000000000000000000000000000000000000'
1856148:1856158:S 18 May 2022 15:11:06.881 * Starting BGSAVE for SYNC with target: disk
1856148:1856158:S 18 May 2022 15:11:06.893 * Background saving started
1856148:1856162:S 18 May 2022 15:11:06.904 * DB saved on disk
1856148:1856162:S 18 May 2022 15:11:06.906 * RDB: 33 MB of memory used by copy-on-write
1856148:1856158:S 18 May 2022 15:11:07.006 * Background saving terminated with success
1856148:1856158:S 18 May 2022 15:11:07.014 * Synchronization with replica 10.1.0.2:6379 succeeded
1856148:1856158:S 18 May 2022 15:11:07.409 * Connecting to MASTER 10.1.0.2:6379
1856148:1856158:S 18 May 2022 15:11:07.409 * MASTER <-> REPLICA sync started
1856148:1856158:S 18 May 2022 15:11:07.412 * Non blocking connect for SYNC fired the event.
1856148:1856158:S 18 May 2022 15:11:07.415 * Master replied to PING, replication can continue...
1856148:1856158:S 18 May 2022 15:11:07.421 * Partial resynchronization not possible (no cached master)
1856148:1856158:S 18 May 2022 15:11:07.438 * Full resync from master: 5ee7555c20391d1be81921a4fc235548d0766dff:11897
1856148:1856158:S 18 May 2022 15:11:07.487 * MASTER <-> REPLICA sync: receiving 136070 bytes from master to disk
1856148:1856158:S 18 May 2022 15:11:07.501 * MASTER <-> REPLICA sync: Loading DB in memory
1856148:1856158:S 18 May 2022 15:11:07.504 * Loading RDB produced by version 6.3.0
1856148:1856158:S 18 May 2022 15:11:07.504 * RDB age 0 seconds
1856148:1856158:S 18 May 2022 15:11:07.504 * RDB memory usage when created 30.80 Mb
1856148:1856158:S 18 May 2022 15:11:07.510 # Done loading RDB, keys loaded: 0, keys expired: 0.
1856148:1856158:S 18 May 2022 15:11:07.510 * RDB contains information on 1 masters
1856148:1856158:S 18 May 2022 15:11:07.510 * MASTER <-> REPLICA sync: Finished with success


=== KEYDB BUG REPORT START: Cut & paste starting from here ===
1856148:1856159:S 18 May 2022 15:21:07.645 # === ASSERTION FAILED ===
1856148:1856159:S 18 May 2022 15:21:07.645 # ==> db.cpp:2863 'o->FExpires() == (m_setexpire->find(sdsKey) != m_setexpire->end())' is not true

------ STACK TRACE ------

Backtrace:
/usr/bin/keydb-server 127.0.0.1:6379(redisDbPersistentData::ensure(char const*, dictEntry**)+0x88f) [0x5563b893a75f]
/usr/bin/keydb-server 127.0.0.1:6379(+0x12c5f3) [0x5563b89435f3]
/usr/bin/keydb-server 127.0.0.1:6379(expireGenericCommand(client*, long long, int)+0x83) [0x5563b88a0163]
/usr/bin/keydb-server 127.0.0.1:6379(call(client*, int)+0xaa) [0x5563b896e60a]
/usr/bin/keydb-server 127.0.0.1:6379(processCommand(client*, int)+0x6fc) [0x5563b896f52c]
/usr/bin/keydb-server 127.0.0.1:6379(processCommandAndResetClient(client*, int)+0x6b) [0x5563b894f56b]
/usr/bin/keydb-server 127.0.0.1:6379(processInputBuffer(client*, bool, int)+0x172) [0x5563b8953302]
/usr/bin/keydb-server 127.0.0.1:6379(processClients()+0x118) [0x5563b89534e8]
/usr/bin/keydb-server 127.0.0.1:6379(+0x14fe6e) [0x5563b8966e6e]
/usr/bin/keydb-server 127.0.0.1:6379(beforeSleep(aeEventLoop*)+0x15a) [0x5563b897a8fa]
/usr/bin/keydb-server 127.0.0.1:6379(aeProcessEvents+0xe3) [0x5563b897e7a3]
/usr/bin/keydb-server 127.0.0.1:6379(aeMain+0x3a) [0x5563b897f6aa]
/usr/bin/keydb-server 127.0.0.1:6379(workerThreadMain(void*)+0x84) [0x5563b8971974]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7fd7448f6609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fd744819133]

------ INFO OUTPUT ------
# Server
redis_version:6.3.0
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:bc455d014a017397
redis_mode:standalone
os:Linux 5.4.0-109-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:9.3.0
process_id:1856148
process_supervised:systemd
run_id:67c985dbc8daccd916b7f2e306fbad01dec2635e
tcp_port:6379
server_time_usec:1652880067645757
uptime_in_seconds:601
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:8712899
executable:/usr/bin/keydb-server
config_file:/etc/keydb/keydb.conf

# Clients
connected_clients:204
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:143
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0
current_client_thread:1
thread_0_clients:102
thread_1_clients:103

# Memory
used_memory:17706128
used_memory_human:16.89M
used_memory_rss:32346112
used_memory_rss_human:30.85M
used_memory_peak:32295544
used_memory_peak_human:30.80M
used_memory_peak_perc:54.83%
used_memory_overhead:15804488
used_memory_startup:10419760
used_memory_dataset:1901640
used_memory_dataset_perc:26.10%
allocator_allocated:18837992
allocator_active:21094400
allocator_resident:27418624
total_system_memory:8144510976
total_system_memory_human:7.59G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:1073741824
maxmemory_human:1.00G
maxmemory_policy:allkeys-lru
allocator_frag_ratio:1.12
allocator_frag_bytes:2256408
allocator_rss_ratio:1.30
allocator_rss_bytes:6324224
rss_overhead_ratio:1.18
rss_overhead_bytes:4927488
mem_fragmentation_ratio:1.83
mem_fragmentation_bytes:14643512
mem_not_counted_for_evict:1048576
mem_replication_backlog:1048576
mem_clients_slaves:20512
mem_clients_normal:4100952
mem_aof_buffer:0
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0
storage_provider:none

# Persistence
loading:0
current_cow_size:34705408
current_cow_size_age:600
current_fork_perc:0.00
current_save_keys_processed:1
current_save_keys_total:0
rdb_changes_since_last_save:4094
rdb_bgsave_in_progress:0
rdb_last_save_time:1652879466
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:34803712
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:668
total_commands_processed:31423
instantaneous_ops_per_sec:804
total_net_input_bytes:3844750
total_net_output_bytes:3837222
instantaneous_input_kbps:101.15
instantaneous_output_kbps:247.77
rejected_connections:0
sync_full:1
sync_partial_ok:0
sync_partial_err:1
expired_keys:332
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:9794
keyspace_misses:1946
pubsub_channels:11
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:25325
total_writes_processed:31124
instantaneous_lock_contention:2
avg_lock_contention:0.343750
storage_provider_read_hits:0
storage_provider_read_misses:0

# Replication
role:active-replica
master_global_link_status:up
connected_masters:1
master_host:10.1.0.2
master_port:6379
master_link_status:up
master_last_io_seconds_ago:0
master_sync_in_progress:0
slave_read_repl_offset:1793636
slave_repl_offset:1792901
slave_priority:100
slave_read_only:0
replica_announced:1
connected_slaves:1
slave0:ip=10.1.0.2,port=6379,state=online,offset=2091343,lag=1
master_failover_state:no-failover
master_replid:768b568dc2903056b9ef5051a7a00da32e537135
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:2168278
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1119703
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:5.643432
used_cpu_user:7.054610
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
server_threads:2
long_lock_waits:392
used_cpu_sys_main_thread:1.233041
used_cpu_user_main_thread:1.725444

# Modules

# Commandstats
cmdstat_publish:calls=472,usec=12346,usec_per_call=26.16,rejected_calls=0,failed_calls=0
cmdstat_set:calls=2581,usec=33188,usec_per_call=12.86,rejected_calls=0,failed_calls=0
cmdstat_replping:calls=1,usec=2,usec_per_call=2.00,rejected_calls=0,failed_calls=0
cmdstat_pexpireat:calls=93,usec=524,usec_per_call=5.63,rejected_calls=0,failed_calls=0
cmdstat_unwatch:calls=19,usec=96,usec_per_call=5.05,rejected_calls=0,failed_calls=0
cmdstat_exists:calls=1013,usec=7739,usec_per_call=7.64,rejected_calls=0,failed_calls=0
cmdstat_replconf:calls=598,usec=1622,usec_per_call=2.71,rejected_calls=0,failed_calls=0
cmdstat_rreplay:calls=8743,usec=113728,usec_per_call=13.01,rejected_calls=0,failed_calls=0
cmdstat_exec:calls=189,usec=5684,usec_per_call=30.07,rejected_calls=0,failed_calls=0
cmdstat_echo:calls=1790,usec=5753,usec_per_call=3.21,rejected_calls=0,failed_calls=0
cmdstat_keys:calls=1,usec=58,usec_per_call=58.00,rejected_calls=0,failed_calls=0
cmdstat_incrby:calls=263,usec=2475,usec_per_call=9.41,rejected_calls=0,failed_calls=0
cmdstat_psync:calls=1,usec=13030,usec_per_call=13030.00,rejected_calls=0,failed_calls=0
cmdstat_watch:calls=145,usec=460,usec_per_call=3.17,rejected_calls=0,failed_calls=0
cmdstat_select:calls=2418,usec=6682,usec_per_call=2.76,rejected_calls=0,failed_calls=0
cmdstat_subscribe:calls=517,usec=2246,usec_per_call=4.34,rejected_calls=0,failed_calls=0
cmdstat_decrby:calls=47,usec=428,usec_per_call=9.11,rejected_calls=0,failed_calls=0
cmdstat_multi:calls=189,usec=187,usec_per_call=0.99,rejected_calls=0,failed_calls=0
cmdstat_get:calls=11263,usec=165685,usec_per_call=14.71,rejected_calls=0,failed_calls=0
cmdstat_ping:calls=59,usec=44,usec_per_call=0.75,rejected_calls=0,failed_calls=0
cmdstat_setex:calls=626,usec=14597,usec_per_call=23.32,rejected_calls=0,failed_calls=0
cmdstat_del:calls=176,usec=1364,usec_per_call=7.75,rejected_calls=0,failed_calls=0
cmdstat_expire:calls=219,usec=1999,usec_per_call=9.13,rejected_calls=0,failed_calls=0

# Errorstats

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=71,expires=1,avg_ttl=0,cached_keys=71
db1:keys=14,expires=0,avg_ttl=0,cached_keys=14
db2:keys=241,expires=162,avg_ttl=2230651,cached_keys=241
db3:keys=11,expires=0,avg_ttl=0,cached_keys=11
db4:keys=56,expires=4,avg_ttl=499975,cached_keys=56
db5:keys=19,expires=0,avg_ttl=0,cached_keys=19
db6:keys=93,expires=72,avg_ttl=400134,cached_keys=93
db7:keys=19,expires=0,avg_ttl=0,cached_keys=19
db8:keys=636,expires=574,avg_ttl=2688126,cached_keys=636
db9:keys=69,expires=43,avg_ttl=3511238,cached_keys=69
db10:keys=19,expires=15,avg_ttl=171592,cached_keys=19
db11:keys=58,expires=38,avg_ttl=146229,cached_keys=58
db12:keys=40,expires=36,avg_ttl=509416,cached_keys=40
db13:keys=24,expires=2,avg_ttl=356329,cached_keys=24
db14:keys=4,expires=0,avg_ttl=0,cached_keys=4
db15:keys=24,expires=0,avg_ttl=0,cached_keys=24
db16:keys=21,expires=6,avg_ttl=102593,cached_keys=21
db17:keys=25,expires=6,avg_ttl=121551,cached_keys=25
db18:keys=7,expires=4,avg_ttl=62078,cached_keys=7
db19:keys=70,expires=16,avg_ttl=145556,cached_keys=70
db20:keys=93,expires=72,avg_ttl=528055,cached_keys=93
db21:keys=25,expires=2,avg_ttl=56272,cached_keys=25
db22:keys=20,expires=6,avg_ttl=292945,cached_keys=20
db23:keys=15,expires=3,avg_ttl=203137,cached_keys=15
db24:keys=426,expires=371,avg_ttl=475712,cached_keys=426
db25:keys=26,expires=20,avg_ttl=502465,cached_keys=26
db26:keys=28,expires=11,avg_ttl=141702,cached_keys=28
db28:keys=15,expires=0,avg_ttl=0,cached_keys=15
db29:keys=27,expires=5,avg_ttl=181142,cached_keys=27
db30:keys=8,expires=0,avg_ttl=0,cached_keys=8
db31:keys=28,expires=0,avg_ttl=0,cached_keys=28
db32:keys=150,expires=29,avg_ttl=169918,cached_keys=150
db33:keys=15,expires=3,avg_ttl=63451,cached_keys=15
db34:keys=23,expires=0,avg_ttl=0,cached_keys=23
db35:keys=21,expires=0,avg_ttl=0,cached_keys=21
db36:keys=19,expires=0,avg_ttl=0,cached_keys=19
db37:keys=15,expires=0,avg_ttl=0,cached_keys=15
db38:keys=5,expires=1,avg_ttl=212456,cached_keys=5
db39:keys=24,expires=4,avg_ttl=67654,cached_keys=24

# KeyDB
mvcc_depth:1
```

**Comment by JohnSully** [comment] 2022-05-19 23:48
This wasn't originally found by our test suite, but I was able to make a change that allowed our tests to reproduce it consistently.  I believe this is a dupe of a few others, but will verify the callstacks once I have the fix.

**Comment by JohnSully** [comment] 2022-05-20 00:00
This can be mitigated by setting "enable-async-commands no"

**Comment by JohnSully** [comment] 2022-05-20 01:51
Fix change: https://github.com/Snapchat/KeyDB/pull/431 

Note this is a dupe of #425 - will close and leave 425 open until this hits the main branch.

**Closed by JohnSully** 2022-05-20 01:51 UTC
