### ISSUE TITLE
[CRASH] KeyDB with Flash enabled crashes with 'Accessing address: 0x3fa8dbc0b360'.

### ISSUE THREAD

**Issue by skolosov-snap** [Snapchat/KeyDB#611] opened 2023-03-20 18:24 UTC
**Crash report**

Paste the complete crash log between the quotes below. Please include a few lines from the log preceding the crash report to provide some context.

```
=== KEYDB BUG REPORT START: Cut & paste starting from here ===
37:78:S 20 Mar 2023 17:50:57.991 # KeyDB 255.255.255 crashed by signal: 11, si_code: 1
37:78:S 20 Mar 2023 17:50:57.991 # Accessing address: 0x3fa8dbc0b360
37:78:S 20 Mar 2023 17:50:57.991 # Crashed running the instruction at: 0x562ffdaf579a

------ STACK TRACE ------
EIP:
keydb-server 0.0.0.0:17379 [cluster](+0x23d79a) [0x562ffdaf579a]

Backtrace:
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f51e0fda420]
keydb-server 0.0.0.0:17379 [cluster](+0x23d79a) [0x562ffdaf579a]
keydb-server 0.0.0.0:17379 [cluster](+0x23ce10) [0x562ffdaf4e10]
keydb-server 0.0.0.0:17379 [cluster](deserializeStoredObject(redisDbPersistentData const*, char const*, void const*, unsigned long)+0x4c) [0x562ffdaf63ec]
keydb-server 0.0.0.0:17379 [cluster](+0x22a744) [0x562ffdae2744]
keydb-server 0.0.0.0:17379 [cluster](RocksDBStorageProvider::retrieve(char const*, unsigned long, std::function<void (char const*, unsigned long, void const*, unsigned long)>) const+0x11f) [0x562ffda1a06f]
keydb-server 0.0.0.0:17379 [cluster](StorageCache::retrieve(char*, std::function<void (char const*, unsigned long, void const*, unsigned long)>) const+0xc2) [0x562ffda208e2]
keydb-server 0.0.0.0:17379 [cluster](redisDbPersistentData::prefetchKeysAsync(client*, parsed_command&)+0x443) [0x562ffdae7423]
keydb-server 0.0.0.0:17379 [cluster](parseClientCommandBuffer(client*)+0x368) [0x562ffdaff388]
keydb-server 0.0.0.0:17379 [cluster](readQueryFromClient(connection*)+0x39a) [0x562ffdaffbda]
keydb-server 0.0.0.0:17379 [cluster](tlsHandleEvent(tls_connection*, int)+0x14d) [0x562ffda290ed]
keydb-server 0.0.0.0:17379 [cluster](ProcessEventCore+0xf9) [0x562ffdb2a119]
keydb-server 0.0.0.0:17379 [cluster](aeProcessEvents+0x17d) [0x562ffdb2b43d]
keydb-server 0.0.0.0:17379 [cluster](aeMain+0x3a) [0x562ffdb2bb7a]
keydb-server 0.0.0.0:17379 [cluster](workerThreadMain(void*)+0x88) [0x562ffdb13e98]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f51e0fce609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f51e0ef1133]

------ REGISTERS ------
37:78:S 20 Mar 2023 17:50:57.993 #
RAX:5555500743054663 RBX:00007f51b78166b8
RCX:000001870113f58d RDX:00003fa8dbc0b350
RDI:2aaaa803a182a331 RSI:00007f51bbffcb20
RBP:00007f517d066270 RSP:00007f51bbffb5f0
R8 :00007f51dfe00900 R9 :0000000000000020
R10:0000000000000010 R11:00007f51bbffe700
R12:00007f51b863f3b8 R13:00007f50d74fbc00
R14:00007f4f749f3330 R15:00007f4f749f3320
RIP:0000562ffdaf579a EFL:0000000000010206
CSGSFS:002b000000000033
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5ff) -> 0000562ffdaf4e10
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5fe) -> 00007f51b863f3b8
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5fd) -> 00007f50e91bc270
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5fc) -> 00007f50e91bc260
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5fb) -> 00007f51b7803df0
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5fa) -> 00007f50d74fbc90
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5f9) -> 00007f50d74fbc00
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5f8) -> 000000000000000c
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5f7) -> 7930ba9e928fc400
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5f6) -> 00007f5065ed887b
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5f5) -> 0000000000000000
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5f4) -> 00007f4f749f3330
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5f3) -> 000000000005b330
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5f2) -> 00007f50d73c6710
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5f1) -> 00007f51b78166b8
37:78:S 20 Mar 2023 17:50:57.993 # (00007f51bbffb5f0) -> 00007f50e37a6ee0

------ INFO OUTPUT ------
# Server
redis_version:255.255.255
redis_git_sha1:8fc48125
redis_git_dirty:1
redis_build_id:e228dd6a36339e3f
redis_mode:cluster
os:Linux 5.10.147+ x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:9.4.0
process_id:37
process_supervised:no
run_id:c6e9872afd44bea744173235001c57ea37b819d5
tcp_port:17379
server_time_usec:1679334657993286
uptime_in_seconds:52939
uptime_in_days:0
hz:40
configured_hz:40
lru_clock:1613057
executable:/data/keydb-server
config_file:/redis-conf/redis.conf
availability_zone:us-central1-c

# Clients
connected_clients:482
cluster_connections:28
maxclients:60000
client_recent_max_input_buffer:1298
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0
current_client_thread:1
thread_0_clients:71
thread_1_clients:71
thread_2_clients:99
thread_3_clients:87
thread_4_clients:80
thread_5_clients:74

# Memory
used_memory:10793646888
used_memory_human:10.05G
used_memory_rss:16062939136
used_memory_rss_human:14.96G
used_memory_peak:10945497320
used_memory_peak_human:10.19G
used_memory_peak_perc:98.61%
used_memory_overhead:2820735724
used_memory_startup:25837960
used_memory_dataset:7972911004
used_memory_dataset_perc:74.04%
allocator_allocated:10644342560
allocator_active:12222648320
allocator_resident:12351270912
total_system_memory:33671958528
total_system_memory_human:31.36G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:8937614131
maxmemory_human:8.32G
maxmemory_policy:allkeys-lfu
allocator_frag_ratio:1.15
allocator_frag_bytes:1578305760
allocator_rss_ratio:1.01
allocator_rss_bytes:128622592
rss_overhead_ratio:1.30
rss_overhead_bytes:3711668224
mem_fragmentation_ratio:1.51
mem_fragmentation_bytes:5421681424
mem_not_counted_for_evict:2000000000
mem_replication_backlog:2147483648
mem_clients_slaves:0
mem_clients_normal:9879836
mem_aof_buffer:0
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0
storage_provider:flash
flash_memory:11592593066

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:135198664
rdb_bgsave_in_progress:0
rdb_last_save_time:1679281718
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:16385
total_commands_processed:182682631
instantaneous_ops_per_sec:5970
total_net_input_bytes:168484559909
total_net_output_bytes:48540302468
instantaneous_input_kbps:5359.60
instantaneous_output_kbps:1693.73
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:42001143
keyspace_misses:5147451
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:169214748
total_writes_processed:47481134
instantaneous_lock_contention:5
avg_lock_contention:0.625000
storage_provider_read_hits:900659
storage_provider_read_misses:7444752

# Replication
role:slave
master_global_link_status:up
connected_masters:1
master_host:10.110.44.85
master_port:17379
master_link_status:up
master_last_io_seconds_ago:0
master_sync_in_progress:0
slave_read_repl_offset:164378198849
slave_repl_offset:164378198849
slave_priority:100
slave_read_only:1
replica_announced:1
connected_slaves:0
master_failover_state:no-failover
master_replid:2aaeffe91b7362d7d856bcc91581eaa636393a61
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:164378198849
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:2000000000
repl_backlog_first_byte_offset:162378198850
repl_backlog_histlen:2000000000

# CPU
used_cpu_sys:6295.464399
used_cpu_user:8965.720951
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
server_threads:6
long_lock_waits:1698
used_cpu_sys_main_thread:138.268193
used_cpu_user_main_thread:242.433066

# Modules
module:name=statsd,ver=1,api=1,filters=0,usedby=[],using=[],options=[]

# Commandstats
cmdstat_get:calls=47148594,usec=185059951,usec_per_call=3.93,rejected_calls=0,failed_calls=0
cmdstat_client:calls=1,usec=2,usec_per_call=2.00,rejected_calls=0,failed_calls=0
cmdstat_ping:calls=309811,usec=208999,usec_per_call=0.67,rejected_calls=0,failed_calls=0
cmdstat_select:calls=1,usec=1,usec_per_call=1.00,rejected_calls=0,failed_calls=0
cmdstat_cluster:calls=14955,usec=764105,usec_per_call=51.09,rejected_calls=0,failed_calls=0
cmdstat_info:calls=5303,usec=345185,usec_per_call=65.09,rejected_calls=0,failed_calls=0
cmdstat_set:calls=129725347,usec=764237861,usec_per_call=5.89,rejected_calls=0,failed_calls=0
cmdstat_dbsize:calls=4813,usec=1538,usec_per_call=0.32,rejected_calls=0,failed_calls=0
cmdstat_readonly:calls=480,usec=279,usec_per_call=0.58,rejected_calls=0,failed_calls=0
cmdstat_del:calls=5473317,usec=313684916,usec_per_call=57.31,rejected_calls=0,failed_calls=0
cmdstat_config:calls=9,usec=605,usec_per_call=67.22,rejected_calls=0,failed_calls=0

# Errorstats

# Cluster
cluster_enabled:1

# Keyspace
db0:keys=8388609,expires=8388609,avg_ttl=32336989,cached_keys=4015047

# KeyDB
mvcc_depth:0

------ CLIENT LIST OUTPUT ------
...
------ MODULES INFO OUTPUT ------

------ FAST MEMORY TEST ------
37:80:S 20 Mar 2023 17:50:58.002 # ------------------------------------------------
37:80:S 20 Mar 2023 17:50:58.002 # !!! Software Failure. Press left mouse button to continue
37:81:S 20 Mar 2023 17:50:58.002 # ------------------------------------------------
37:81:S 20 Mar 2023 17:50:58.002 # !!! Software Failure. Press left mouse button to continue
37:79:S 20 Mar 2023 17:50:58.002 # ------------------------------------------------
37:81:S 20 Mar 2023 17:50:58.002 # Guru Meditation: fastlock lock/unlock mismatch for: client 219 #fastlock.cpp:295
37:80:S 20 Mar 2023 17:50:58.002 # Guru Meditation: fastlock lock/unlock mismatch for: client 131 #fastlock.cpp:295
37:79:S 20 Mar 2023 17:50:58.002 # !!! Software Failure. Press left mouse button to continue
37:79:S 20 Mar 2023 17:50:58.002 # Guru Meditation: fastlock lock/unlock mismatch for: client 122 #fastlock.cpp:295
37:78:S 20 Mar 2023 17:50:58.002 # main thread terminated

------ STACK TRACE ------

Backtrace:

------ STACK TRACE ------

Backtrace:

------ STACK TRACE ------

Backtrace:
37:78:S 20 Mar 2023 17:50:58.002 # Bio thread for job type #0 terminated
37:78:S 20 Mar 2023 17:50:58.002 # Bio thread for job type #1 terminated
37:78:S 20 Mar 2023 17:50:58.002 # Bio thread for job type #2 terminated

Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.
keydb-server 0.0.0.0:17379 [cluster](+0x15da27) [0x562ffda15a27]
keydb-server 0.0.0.0:17379 [cluster](+0x115f69) [0x562ffd9cdf69]
keydb-server 0.0.0.0:17379 [cluster](tlsHandleEvent(tls_connection*, int)+0x14d) [0x562ffda290ed]
keydb-server 0.0.0.0:17379 [cluster](ProcessEventCore+0xf9) [0x562ffdb2a119]
keydb-server 0.0.0.0:17379 [cluster](aeProcessEvents+0x17d) [0x562ffdb2b43d]
keydb-server 0.0.0.0:17379 [cluster](aeMain+0x3a) [0x562ffdb2bb7a]
keydb-server 0.0.0.0:17379 [cluster](workerThreadMain(void*)+0x88) [0x562ffdb13e98]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f51e0fce609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f51e0ef1133]

------ INFO OUTPUT ------
# Server
redis_version:255.255.255
redis_git_sha1:8fc48125
redis_git_dirty:1
redis_build_id:e228dd6a36339e3f
redis_mode:cluster
os:Linux 5.10.147+ x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:9.4.0
process_id:37
process_supervised:no
run_id:c6e9872afd44bea744173235001c57ea37b819d5
tcp_port:17379
server_time_usec:1679334658004306
uptime_in_seconds:52940
uptime_in_days:0
hz:40
configured_hz:40
lru_clock:1613057
executable:/data/keydb-server
config_file:/redis-conf/redis.conf
availability_zone:us-central1-c

# Clients
connected_clients:482
cluster_connections:28
maxclients:60000
client_recent_max_input_buffer:1298
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0
current_client_thread:4
thread_0_clients:71
thread_1_clients:71
thread_2_clients:99
thread_3_clients:87
thread_4_clients:80
thread_5_clients:74

# Memory
used_memory:10793817632
used_memory_human:10.05G
used_memory_rss:16062939136
used_memory_rss_human:14.96G
used_memory_peak:10945497320
used_memory_peak_human:10.19G
used_memory_peak_perc:98.61%
used_memory_overhead:2820735724
used_memory_startup:25837960
used_memory_dataset:7973081908
used_memory_dataset_perc:74.04%
allocator_allocated:10644342560
allocator_active:12222648320
allocator_resident:12351270912
total_system_memory:33671958528
total_system_memory_human:31.36G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:8937614131
maxmemory_human:8.32G
maxmemory_policy:allkeys-lfu
allocator_frag_ratio:1.15
allocator_frag_bytes:1578305760
allocator_rss_ratio:1.01
allocator_rss_bytes:128622592
rss_overhead_ratio:1.30
rss_overhead_bytes:3711668224
mem_fragmentation_ratio:1.51
mem_fragmentation_bytes:5421681424
mem_not_counted_for_evict:2000000000
mem_replication_backlog:2147483648
mem_clients_slaves:0
mem_clients_normal:9879836
mem_aof_buffer:0
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0
storage_provider:flash
flash_memory:11592593066

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:135198664
rdb_bgsave_in_progress:0
rdb_last_save_time:1679281718
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:16385
total_commands_processed:182682632
instantaneous_ops_per_sec:5970
total_net_input_bytes:168484559909
total_net_output_bytes:48540302468
instantaneous_input_kbps:5359.60
instantaneous_output_kbps:1693.73
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:42001144
keyspace_misses:5147451
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:169214748
total_writes_processed:47481134
instantaneous_lock_contention:4
avg_lock_contention:0.625000
storage_provider_read_hits:900659
storage_provider_read_misses:7444752

# Replication
role:slave
master_global_link_status:up
connected_masters:1
master_host:10.110.44.85
master_port:17379
master_link_status:up
master_last_io_seconds_ago:1
master_sync_in_progress:0
slave_read_repl_offset:164378198849
slave_repl_offset:164378198849
slave_priority:100
slave_read_only:1
replica_announced:1
connected_slaves:0
master_failover_state:no-failover
master_replid:2aaeffe91b7362d7d856bcc91581eaa636393a61
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:164378198849
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:2000000000
repl_backlog_first_byte_offset:162378198850
repl_backlog_histlen:2000000000

# CPU
used_cpu_sys:6295.464399
used_cpu_user:8965.769360
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
server_threads:6
long_lock_waits:1698
used_cpu_sys_main_thread:238.375673
used_cpu_user_main_thread:393.461654

# Modules
module:name=statsd,ver=1,api=1,filters=0,usedby=[],using=[],options=[]

# Commandstats
cmdstat_get:calls=47148595,usec=185066459,usec_per_call=3.93,rejected_calls=0,failed_calls=0
cmdstat_client:calls=1,usec=2,usec_per_call=2.00,rejected_calls=0,failed_calls=0
cmdstat_ping:calls=309811,usec=208999,usec_per_call=0.67,rejected_calls=0,failed_calls=0
cmdstat_select:calls=1,usec=1,usec_per_call=1.00,rejected_calls=0,failed_calls=0
cmdstat_cluster:calls=14955,usec=764105,usec_per_call=51.09,rejected_calls=0,failed_calls=0
cmdstat_info:calls=5303,usec=345185,usec_per_call=65.09,rejected_calls=0,failed_calls=0
cmdstat_set:calls=129725347,usec=764237861,usec_per_call=5.89,rejected_calls=0,failed_calls=0
cmdstat_dbsize:calls=4813,usec=1538,usec_per_call=0.32,rejected_calls=0,failed_calls=0
cmdstat_readonly:calls=480,usec=279,usec_per_call=0.58,rejected_calls=0,failed_calls=0
cmdstat_del:calls=5473317,usec=313684916,usec_per_call=57.31,rejected_calls=0,failed_calls=0
cmdstat_config:calls=9,usec=605,usec_per_call=67.22,rejected_calls=0,failed_calls=0

# Errorstats

# Cluster
cluster_enabled:1

# Keyspace
db0:keys=8388609,expires=8388609,avg_ttl=32336980,cached_keys=4015047

# KeyDB
mvcc_depth:0

------ CLIENT LIST OUTPUT ------
37:81:S 20 Mar 2023 17:50:58.004 # ------------------------------------------------
37:81:S 20 Mar 2023 17:50:58.004 # !!! Software Failure. Press left mouse button to continue
37:81:S 20 Mar 2023 17:50:58.004 # Guru Meditation: fastlock lock/unlock mismatch for: client 122 #fastlock.cpp:295

------ STACK TRACE ------

Backtrace:
keydb-server 0.0.0.0:17379 [cluster](+0x15da27) [0x562ffda15a27]
keydb-server 0.0.0.0:17379 [cluster](+0x115f69) [0x562ffd9cdf69]
keydb-server 0.0.0.0:17379 [cluster](tlsHandleEvent(tls_connection*, int)+0x14d) [0x562ffda290ed]
keydb-server 0.0.0.0:17379 [cluster](ProcessEventCore+0xf9) [0x562ffdb2a119]
keydb-server 0.0.0.0:17379 [cluster](aeProcessEvents+0x17d) [0x562ffdb2b43d]
keydb-server 0.0.0.0:17379 [cluster](aeMain+0x3a) [0x562ffdb2bb7a]
keydb-server 0.0.0.0:17379 [cluster](workerThreadMain(void*)+0x88) [0x562ffdb13e98]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f51e0fce609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f51e0ef1133]

------ INFO OUTPUT ------

------ DUMPING CODE AROUND EIP ------
Symbol: (null) (base: (nil))
Module: keydb-server 0.0.0.0:17379 [cluster] (base 0x562ffd8b8000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=(nil) -D -b binary -m i386:x86-64 /tmp/dump.bin
------

=== KEYDB BUG REPORT END. Make sure to include from START to END. ===
```

**Aditional information**

1. OS distribution and version
2. Steps to reproduce (if any)

**Comment by msotheeswaran** [comment] 2023-03-27 20:49
dupe of #597

**Closed by msotheeswaran** 2023-03-27 20:49 UTC
Labels: Priority 1
