### ISSUE TITLE
[CRASH] Active replicas crashed during RDB network transfer

### ISSUE THREAD

**Issue by reneklacan** [Snapchat/KeyDB#445] opened 2022-06-08 09:42 UTC
**Crash report**

https://gist.github.com/reneklacan/f3fcd8aee08605f0f808abd1b72c63d8

**Aditional information**

OS distribution and version: `Linux 5.4.0-1073-gcp #78~18.04.1-Ubuntu SMP Wed Apr 27 09:05:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
KeyDB version: `6.3.1`

1. We have 2 node active-replica setup
4. Upgraded first server from 6.2 to 6.3 and let it full resync from other node on 6.2
5. Stopped keydb on second server and upgraded to 6.3
6. Started keydb on second server
7. After first keydb did dump, it started sending it to second keydb
8. Both instances crashed around 0.5% progress during sending dump

**Comment by R4scal** [comment] 2022-06-11 09:24
I have some issue with 6.3.1%

```
=== KEYDB BUG REPORT START: Cut & paste starting from here ===
25600:25608:S 11 Jun 2022 09:21:18.107 # === ASSERTION FAILED ===
25600:25608:S 11 Jun 2022 09:21:18.107 # ==> scripting.cpp:780 '(c->flags & CLIENT_BLOCKED) == 0' is not true

------ STACK TRACE ------

Backtrace:
/usr/bin/keydb-server 0.0.0.0:6379(luaRedisGenericCommand(lua_State*, int)+0xe55) [0x5603696e8205]
/usr/bin/keydb-server 0.0.0.0:6379(+0x17839c) [0x56036979e39c]
/usr/bin/keydb-server 0.0.0.0:6379(+0x181e95) [0x5603697a7e95]
/usr/bin/keydb-server 0.0.0.0:6379(+0x17893d) [0x56036979e93d]
/usr/bin/keydb-server 0.0.0.0:6379(+0x177c43) [0x56036979dc43]
/usr/bin/keydb-server 0.0.0.0:6379(+0x178ae1) [0x56036979eae1]
/usr/bin/keydb-server 0.0.0.0:6379(lua_pcall+0x5c) [0x56036979c21c]
/usr/bin/keydb-server 0.0.0.0:6379(evalGenericCommand(client*, int)+0x2bc) [0x5603696e5e3c]
/usr/bin/keydb-server 0.0.0.0:6379(call(client*, int)+0xaa) [0x56036977d44a]
/usr/bin/keydb-server 0.0.0.0:6379(processCommand(client*, int)+0x6fc) [0x56036977e36c]
/usr/bin/keydb-server 0.0.0.0:6379(processCommandAndResetClient(client*, int)+0x6b) [0x56036975e65b]
/usr/bin/keydb-server 0.0.0.0:6379(processInputBuffer(client*, bool, int)+0x172) [0x560369762432]
/usr/bin/keydb-server 0.0.0.0:6379(readQueryFromClient(connection*)+0x6d3) [0x560369762d93]
/usr/bin/keydb-server 0.0.0.0:6379(connSocketEventHandler(aeEventLoop*, int, void*, int)+0x1a0) [0x56036968f6a0]
/usr/bin/keydb-server 0.0.0.0:6379(ProcessEventCore+0xf1) [0x56036978c261]
/usr/bin/keydb-server 0.0.0.0:6379(aeProcessEvents+0x1e5) [0x56036978d4b5]
/usr/bin/keydb-server 0.0.0.0:6379(aeMain+0x3a) [0x56036978db2a]
/usr/bin/keydb-server 0.0.0.0:6379(workerThreadMain(void*)+0x84) [0x560369775d04]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f9732d6a609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f9732c8f293]

------ INFO OUTPUT ------
# Server
redis_version:6.3.1
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:819cc17263ba9399
redis_mode:standalone
os:Linux 5.4.0-52-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:9.3.0
process_id:25600
process_supervised:no
run_id:529b86c7dba5dbcff4d3866d73d11d32b4815d9d
tcp_port:6379
server_time_usec:1654939278109849
uptime_in_seconds:60
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:10772110
executable:/usr/bin/keydb-server
config_file:/etc/keydb/keydb-server.conf

# Clients
connected_clients:29
cluster_connections:0
maxclients:1000
client_recent_max_input_buffer:48
client_recent_max_output_buffer:0
blocked_clients:1
tracking_clients:0
clients_in_timeout_table:0
current_client_thread:0
thread_0_clients:29

# Memory
used_memory:561800520
used_memory_human:535.77M
used_memory_rss:604844032
used_memory_rss_human:576.82M
used_memory_peak:562004880
used_memory_peak_human:535.97M
used_memory_peak_perc:99.96%
used_memory_overhead:4156664
used_memory_startup:580136
used_memory_dataset:557643856
used_memory_dataset_perc:99.36%
allocator_allocated:562279824
allocator_active:625475584
allocator_resident:634683392
total_system_memory:16791572480
total_system_memory_human:15.64G
used_memory_lua:53248
used_memory_lua_human:52.00K
used_memory_scripts:3280
used_memory_scripts_human:3.20K
number_of_cached_scripts:6
maxmemory:2147483648
maxmemory_human:2.00G
maxmemory_policy:noeviction
allocator_frag_ratio:1.11
allocator_frag_bytes:63195760
allocator_rss_ratio:1.01
allocator_rss_bytes:9207808
rss_overhead_ratio:0.95
rss_overhead_bytes:-29839360
mem_fragmentation_ratio:1.08
mem_fragmentation_bytes:43161176
mem_not_counted_for_evict:1048576
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:595128
mem_aof_buffer:0
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0
storage_provider:none

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:1255
rdb_bgsave_in_progress:0
rdb_last_save_time:1654939218
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:29
total_commands_processed:2417
instantaneous_ops_per_sec:29
total_net_input_bytes:172751
total_net_output_bytes:55945
instantaneous_input_kbps:2.05
instantaneous_output_kbps:0.12
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:213
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:4
dump_payload_sanitizations:0
total_reads_processed:224
total_writes_processed:223
instantaneous_lock_contention:2
avg_lock_contention:1.000000
storage_provider_read_hits:0
storage_provider_read_misses:0

# Replication
role:active-replica
master_global_link_status:down
connected_masters:0
master_host:10.151.0.55
master_port:6379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:0
slave_read_repl_offset:1
slave_repl_offset:1
master_link_down_since_seconds:-1
master_1_host:10.151.0.54
master_1_port:6379
master_1_link_status:down
master_1_last_io_seconds_ago:-1
master_1_sync_in_progress:0
slave_read_repl_offset:0
slave_repl_offset:0
master_1_link_down_since_seconds:-1
slave_priority:100
slave_read_only:0
replica_announced:1
connected_slaves:0
master_failover_state:no-failover
master_replid:94e56aad9eb5ef024a879ac85fc2c4c73fc36a9c
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:15290123753880
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:1.026836
used_cpu_user:2.243303
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
server_threads:1
long_lock_waits:0
used_cpu_sys_main_thread:0.061736
used_cpu_user_main_thread:0.175690

# Modules

# Commandstats
cmdstat_rpush:calls=1062,usec=4407,usec_per_call=4.15,rejected_calls=0,failed_calls=0
cmdstat_exec:calls=3,usec=270,usec_per_call=90.00,rejected_calls=0,failed_calls=0
cmdstat_scan:calls=74,usec=1609,usec_per_call=21.74,rejected_calls=0,failed_calls=0
cmdstat_multi:calls=3,usec=2,usec_per_call=0.67,rejected_calls=0,failed_calls=0
cmdstat_psetex:calls=64,usec=737,usec_per_call=11.52,rejected_calls=0,failed_calls=0
cmdstat_unwatch:calls=1,usec=3,usec_per_call=3.00,rejected_calls=0,failed_calls=0
cmdstat_auth:calls=29,usec=167,usec_per_call=5.76,rejected_calls=0,failed_calls=0
cmdstat_exists:calls=1,usec=4,usec_per_call=4.00,rejected_calls=0,failed_calls=0
cmdstat_set:calls=1,usec=70,usec_per_call=70.00,rejected_calls=0,failed_calls=0
cmdstat_hkeys:calls=1,usec=7,usec_per_call=7.00,rejected_calls=0,failed_calls=0
cmdstat_config:calls=4,usec=10,usec_per_call=2.50,rejected_calls=0,failed_calls=4
cmdstat_llen:calls=211,usec=100,usec_per_call=0.47,rejected_calls=0,failed_calls=0
cmdstat_info:calls=5,usec=850,usec_per_call=170.00,rejected_calls=0,failed_calls=0
cmdstat_keys:calls=1,usec=6754,usec_per_call=6754.00,rejected_calls=0,failed_calls=0
cmdstat_watch:calls=1,usec=4,usec_per_call=4.00,rejected_calls=0,failed_calls=0
cmdstat_setnx:calls=956,usec=1441,usec_per_call=1.51,rejected_calls=0,failed_calls=0

# Errorstats
errorstat_ERR:count=4

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=74227,expires=17,avg_ttl=10893,cached_keys=74227

# KeyDB
mvcc_depth:1

------ CLIENT LIST OUTPUT ------
id=5 addr=127.0.0.1:38610 laddr=127.0.0.1:6379 fd=14 name= age=60 idle=60 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20520 events=r cmd=config user=default redir=-1
id=27 addr=127.0.0.1:38658 laddr=127.0.0.1:6379 fd=36 name= age=53 idle=6 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20512 events=r cmd=setnx user=default redir=-1
id=30 addr=127.0.0.1:38664 laddr=127.0.0.1:6379 fd=39 name= age=15 idle=6 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20512 events=r cmd=setnx user=default redir=-1
id=21 addr=127.0.0.1:38644 laddr=127.0.0.1:6379 fd=30 name= age=56 idle=11 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=6 addr=127.0.0.1:38612 laddr=127.0.0.1:6379 fd=15 name= age=60 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=40954 argv-mem=62 obl=0 oll=0 omem=0 tot-mem=61534 events=r cmd=evalsha user=default redir=-1
id=25 addr=127.0.0.1:38654 laddr=127.0.0.1:6379 fd=34 name= age=54 idle=6 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20512 events=r cmd=rpush user=default redir=-1
id=26 addr=127.0.0.1:38656 laddr=127.0.0.1:6379 fd=35 name= age=54 idle=7 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20512 events=r cmd=setnx user=default redir=-1
id=7 addr=127.0.0.1:38614 laddr=127.0.0.1:6379 fd=16 name= age=60 idle=60 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20520 events=r cmd=config user=default redir=-1
id=8 addr=127.0.0.1:38618 laddr=127.0.0.1:6379 fd=17 name= age=57 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=19 addr=127.0.0.1:38640 laddr=127.0.0.1:6379 fd=28 name= age=56 idle=11 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=20 addr=127.0.0.1:38642 laddr=127.0.0.1:6379 fd=29 name= age=56 idle=11 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=14 addr=127.0.0.1:38630 laddr=127.0.0.1:6379 fd=23 name= age=57 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=15 addr=127.0.0.1:38632 laddr=127.0.0.1:6379 fd=24 name= age=57 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=16 addr=127.0.0.1:38634 laddr=127.0.0.1:6379 fd=25 name= age=57 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=17 addr=127.0.0.1:38636 laddr=127.0.0.1:6379 fd=26 name= age=57 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=23 addr=127.0.0.1:38648 laddr=127.0.0.1:6379 fd=32 name= age=56 idle=11 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=24 addr=127.0.0.1:38652 laddr=127.0.0.1:6379 fd=33 name= age=55 idle=52 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20512 events=r cmd=setnx user=default redir=-1
id=31 addr=127.0.0.1:38670 laddr=127.0.0.1:6379 fd=40 name= age=8 idle=2 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20512 events=r cmd=setnx user=default redir=-1
id=18 addr=127.0.0.1:38638 laddr=127.0.0.1:6379 fd=27 name= age=57 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=9 addr=127.0.0.1:38620 laddr=127.0.0.1:6379 fd=18 name= age=57 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=10 addr=127.0.0.1:38622 laddr=127.0.0.1:6379 fd=19 name= age=57 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=32 addr=127.0.0.1:38672 laddr=127.0.0.1:6379 fd=41 name= age=8 idle=6 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20512 events=r cmd=setnx user=default redir=-1
id=11 addr=127.0.0.1:38624 laddr=127.0.0.1:6379 fd=20 name= age=57 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=22 addr=127.0.0.1:38646 laddr=127.0.0.1:6379 fd=31 name= age=56 idle=11 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=28 addr=127.0.0.1:38660 laddr=127.0.0.1:6379 fd=37 name= age=53 idle=7 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20512 events=r cmd=rpush user=default redir=-1
id=29 addr=127.0.0.1:38662 laddr=127.0.0.1:6379 fd=38 name= age=46 idle=7 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20504 events=r cmd=info user=default redir=-1
id=12 addr=127.0.0.1:38626 laddr=127.0.0.1:6379 fd=21 name= age=57 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=40954 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61480 events=r cmd=set user=default redir=-1
id=13 addr=127.0.0.1:38628 laddr=127.0.0.1:6379 fd=22 name= age=57 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20528 events=r cmd=psetex user=default redir=-1
id=4 addr=127.0.0.1:38608 laddr=127.0.0.1:6379 fd=13 name= age=60 idle=60 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20520 events=r cmd=config user=default redir=-1

------ CURRENT CLIENT INFO ------
id=6 addr=127.0.0.1:38612 laddr=127.0.0.1:6379 fd=15 name= age=60 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=40954 argv-mem=62 obl=0 oll=0 omem=0 tot-mem=61534 events=r cmd=evalsha user=default redir=-1
argv[0]: 'EVALSHA'
argv[1]: '7f2b6080c0be1a8155b56c3b957a595b4b64107b'
argv[2]: '1'
argv[3]: 'incoming128-37'

------ MODULES INFO OUTPUT ------

------ FAST MEMORY TEST ------
25600:25608:S 11 Jun 2022 09:21:18.111 # main thread terminated
25600:25608:S 11 Jun 2022 09:21:18.111 # Bio thread for job type #0 terminated
25600:25608:S 11 Jun 2022 09:21:18.111 # Bio thread for job type #1 terminated
25600:25608:S 11 Jun 2022 09:21:18.111 # Bio thread for job type #2 terminated

Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

=== KEYDB BUG REPORT END. Make sure to include from START to END. ===
```

**Comment by agosalvez** [comment] 2022-06-13 08:52
Hi, @reneklacan 

Do you use docker/k8s?

**Comment by reneklacan** [comment] 2022-06-16 15:22
@agosalvez standalone (GCP VM solely running only KeyDB and nothing else)

**Comment by msotheeswaran** [comment] 2023-02-02 20:56
Could any of you share your config, data, and load on servers during crash to help me reproduce the issue?

**Comment by reneklacan** [comment] 2023-02-03 18:52
@msotheeswaran it has been more than 6 months now so I don't have any additional info anymore, after numerous issues we abandoned KeyDB

**Comment by msotheeswaran** [comment] 2023-02-27 21:26
Closing as I am unable to reproduce and it seems no one else is currently facing this issue.

**Closed by msotheeswaran** 2023-02-27 21:26 UTC
Labels: Priority 1
