### ISSUE TITLE
[BUG] keydb 6.3.2 active-active queue race conditions

### ISSUE THREAD

**Issue by fannyfan414** [Snapchat/KeyDB#553] opened 2023-01-23 10:08 UTC
**Describe the bug**

Hey! In release 6.3.2, I saw a mention that **race conditions** were fixed, but they are still present.

**To reproduce**
I use 2 instances of keydb in active-active mode as queue with [laravel horizon](https://laravel.com/docs/9.x/horizon).
**One job** insert **one record** to mysql table. I setup 80 workers, so they can process 80 jobs **in parallel.**
Then i push 100.000 jobs and got 100.358 records in database.

If i use keydb without active-active mode **as single instance**, i got 100.000 records in database

**Config**
```
--active-replica yes
--appendonly no
--stop-writes-on-bgsave-error no
--save ""
--repl-diskless-sync yes
--server-threads 1
--tcp-backlog 65535"
```

**Comment by msotheeswaran** [comment] 2023-01-23 20:43
HI @fannyfan414 can you provide more details, what specific RESP commands are you sending to KeyDB, are you sending them in parallel to both instances or just one? You mentioned "100.000 jobs and got 100.358 records" if the jobs are sending 1 key each there are 100.000 unique keys sent to KeyDB so there cannot be more than 100.000 records, how are you getting the number of records?

**Comment by msotheeswaran** [comment] 2023-01-23 21:44
> It seems to me that the number of records in the database turns out to be greater than the number of jobs, since several workers try to take on the same job, send requests to different keydb instances and keydb gives each of them this job without having time to synchronize between active-active instances

Do you know how "keydb gives each of them this job", do these workers run a get command against keydb, does this use pubsub?

**Comment by msotheeswaran** [comment] 2023-01-24 20:18
@fannyfan414 it looks like the issue is that 2 parallel workers will pop the same list at the same time on 2 different keydb servers, unfortunately there will always be a delay in synchronization, thus there is no way to support this behaviour with active-active replication. I would suggest either using cluster mode or partitioning the jobs across workers such that no 2 parallel workers will attempt to pop the same list.

**Comment by msotheeswaran** [comment] 2023-01-24 20:53
@fannyfan414 unfortunately we cannot synchronize in the middle of executing a command, in this case both servers would be in the middle of executing the lpop and thus would not be able to accept the synchronization request from the other. If you were to try syncing on each command performance would be completely unreasonable. 

> And if i try to change the logic so that the workers wait until one takes the task, then performance will suffer greatly ..
 Is it possible to partition the workers over the queues, for example worker 1 only takes from queue "a" and worker 2 only takes from queue "b", this way each worker does not need to wait and also will not interfere with other workers.

**Comment by msotheeswaran** [comment] 2023-01-24 22:00
@fannyfan414 unfortunately I don't think active-active is the correct solution, syncing on every command would result in worse performance than just running a single server... perhaps you could try cluster mode with a proxy that will abstract the cluster topology away from horizon, such as https://github.com/RedisLabs/redis-cluster-proxy.

**Comment by msotheeswaran** [comment] 2023-01-25 17:24
@fannyfan414 If you the main concern is fault tolerance, the solution is to simply only write to 1 server at a time, unfortunately it is not an analogue of galera/percona, active-active simply allows masters to sync with each other using time stamps to resolve conflicts, there is no guarantee that all writes will be fully synchronous. The main purpose of active-active was to simplify failover(no need to promote a new master when the master fails, just switch writes to another node).

In cluster mode each queue will be owned by 1 master so this race condition does not exist. Each master can have replicas which can take over as master if the master becomes unavailable, the proxy will handle routing queries so the failover process will become transparent to the client.

**Comment by msotheeswaran** [comment] 2023-02-02 20:34
Going to close this issue as there is no bug in KeyDB, and it seems you have a solution for your use case

**Closed by msotheeswaran** 2023-02-02 20:34 UTC
Labels: More info needed
