### ISSUE TITLE
[BUG] Multi-Master replication issues

### ISSUE THREAD

**Issue by Mall0c** [Snapchat/KeyDB#442] opened 2022-06-03 11:42 UTC
**Describe the bug**
Hello,
I have encountered the following scenarios, where replication did not work as intended:

Issue 1:
- Shutdown both KeyDB instances with `systemctl stop keydb`
- Go to `/var/lib/keydb` (or wherever your `.rdb` file resides) and delete it on both instances to have a fresh start
- Start both KeyDB instances
- Delete one key `key-1`. 
- After that, KeyDB on VM1 is shutdown with `systemctl stop keydb`. 
- In the meantime, the keys `key-2` and `key-3` are deleted in KeyDB on VM2. 
- Running `keys *` on VM2 confirms that these keys are indeed not there anymore.
- When KeyDB on VM1 is started again, e.g. after five seconds, `key-2` and `key-3` reappear. `key-1` remains deleted as intended. However, `key-2` and `key-3` somehow found their way back.
- I came across this when I was testing a client library for node.js in the first place, but for reproduction the `DEL` commands can also be issued from the keydb-cli.

VM1:
```
546:signal-handler (1654255645) Received SIGTERM scheduling shutdown...
546:signal-handler (1654255645) Received SIGTERM scheduling shutdown...
546:552:S 03 Jun 2022 13:27:25.284 # User requested shutdown...
546:552:S 03 Jun 2022 13:27:25.284 * Saving the final RDB snapshot before exiting.
546:552:S 03 Jun 2022 13:27:25.299 * DB saved on disk
546:552:S 03 Jun 2022 13:27:25.299 * Removing the pid file.
546:552:S 03 Jun 2022 13:27:25.299 # KeyDB is now ready to exit, bye bye...
562:562:C 03 Jun 2022 13:27:30.842 * Notice: "active-replica yes" implies "replica-read-only no"
562:562:C 03 Jun 2022 13:27:30.842 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
563:562:C 03 Jun 2022 13:27:30.844 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
563:562:C 03 Jun 2022 13:27:30.844 # KeyDB version=6.2.2, bits=64, commit=00000000, modified=0, pid=563, just started
563:562:C 03 Jun 2022 13:27:30.844 # Configuration loaded
563:562:C 03 Jun 2022 13:27:30.844 # WARNING: server-threads is greater than this machine's core count.  Truncating to 1 threads
563:562:S 03 Jun 2022 13:27:30.844 * monotonic clock: POSIX clock_gettime
563:562:S 03 Jun 2022 13:27:30.845 # Server initialized
563:562:S 03 Jun 2022 13:27:30.845 * Loading RDB produced by version 6.2.2
563:562:S 03 Jun 2022 13:27:30.845 * RDB age 5 seconds
563:562:S 03 Jun 2022 13:27:30.845 * RDB memory usage when created 129.51 Mb
563:562:S 03 Jun 2022 13:27:30.845 # Done loading RDB, keys loaded: 8, keys expired: 0.
563:562:S 03 Jun 2022 13:27:30.845 * DB loaded from disk: 0.000 seconds
563:562:S 03 Jun 2022 13:27:30.845 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
563:569:S 03 Jun 2022 13:27:30.845 * Thread 0 alive.
563:569:S 03 Jun 2022 13:27:30.846 * Connecting to MASTER 192.168.122.2:6379
563:569:S 03 Jun 2022 13:27:30.847 * MASTER <-> REPLICA sync started
563:569:S 03 Jun 2022 13:27:30.847 * Non blocking connect for SYNC fired the event.
563:569:S 03 Jun 2022 13:27:30.847 * Master replied to PING, replication can continue...
563:569:S 03 Jun 2022 13:27:30.847 * Partial resynchronization not possible (no cached master)
563:569:S 03 Jun 2022 13:27:30.848 * Full resync from master: b2822990e65417b03d59e94001727add8be69492:6016
563:569:S 03 Jun 2022 13:27:30.848 * Discarding previously cached master state.
563:569:S 03 Jun 2022 13:27:30.877 * MASTER <-> REPLICA sync: receiving 517 bytes from master to disk
563:569:S 03 Jun 2022 13:27:30.877 * MASTER <-> REPLICA sync: Loading DB in memory
563:569:S 03 Jun 2022 13:27:30.885 * Loading RDB produced by version 6.2.2
563:569:S 03 Jun 2022 13:27:30.885 * RDB age 0 seconds
563:569:S 03 Jun 2022 13:27:30.885 * RDB memory usage when created 129.59 Mb
563:569:S 03 Jun 2022 13:27:30.885 # Done loading RDB, keys loaded: 6, keys expired: 0.
563:569:S 03 Jun 2022 13:27:30.885 * MASTER <-> REPLICA sync: Finished with success
563:569:S 03 Jun 2022 13:27:31.084 * Replica 192.168.122.2:6379 asks for synchronization
563:569:S 03 Jun 2022 13:27:31.084 * Full resync requested by replica 192.168.122.2:6379
563:569:S 03 Jun 2022 13:27:31.084 * Starting BGSAVE for SYNC with target: disk
563:569:S 03 Jun 2022 13:27:31.085 * Background saving started by pid 570
570:569:C 03 Jun 2022 13:27:31.103 * DB saved on disk
570:569:C 03 Jun 2022 13:27:31.105 * RDB: 0 MB of memory used by copy-on-write
563:569:S 03 Jun 2022 13:27:31.150 * Background saving terminated with success
563:569:S 03 Jun 2022 13:27:31.150 * Synchronization with replica 192.168.122.2:6379 succeeded
```

VM2:
```
1152:1159:S 03 Jun 2022 13:27:25.294 # Connection with replica 192.168.122.70:6379 lost.
1152:1159:S 03 Jun 2022 13:27:25.294 # Connection with master lost.
1152:1159:S 03 Jun 2022 13:27:25.294 * Caching the disconnected master state.
1152:1159:S 03 Jun 2022 13:27:26.015 * Connecting to MASTER 192.168.122.70:6379
1152:1159:S 03 Jun 2022 13:27:26.016 * MASTER <-> REPLICA sync started
1152:1159:S 03 Jun 2022 13:27:26.016 # Error condition on socket for SYNC: Connection refused
1152:1159:S 03 Jun 2022 13:27:27.025 * Connecting to MASTER 192.168.122.70:6379
1152:1159:S 03 Jun 2022 13:27:27.025 * MASTER <-> REPLICA sync started
1152:1159:S 03 Jun 2022 13:27:27.025 # Error condition on socket for SYNC: Connection refused
1152:1159:S 03 Jun 2022 13:27:28.035 * Connecting to MASTER 192.168.122.70:6379
1152:1159:S 03 Jun 2022 13:27:28.035 * MASTER <-> REPLICA sync started
1152:1159:S 03 Jun 2022 13:27:28.036 # Error condition on socket for SYNC: Connection refused
1152:1159:S 03 Jun 2022 13:27:29.047 * Connecting to MASTER 192.168.122.70:6379
1152:1159:S 03 Jun 2022 13:27:29.047 * MASTER <-> REPLICA sync started
1152:1159:S 03 Jun 2022 13:27:29.048 # Error condition on socket for SYNC: Connection refused
1152:1159:S 03 Jun 2022 13:27:30.058 * Connecting to MASTER 192.168.122.70:6379
1152:1159:S 03 Jun 2022 13:27:30.058 * MASTER <-> REPLICA sync started
1152:1159:S 03 Jun 2022 13:27:30.059 # Error condition on socket for SYNC: Connection refused
1152:1159:S 03 Jun 2022 13:27:30.839 * Replica 192.168.122.70:6379 asks for synchronization
1152:1159:S 03 Jun 2022 13:27:30.839 * Full resync requested by replica 192.168.122.70:6379
1152:1159:S 03 Jun 2022 13:27:30.839 * Starting BGSAVE for SYNC with target: disk
1152:1159:S 03 Jun 2022 13:27:30.840 * Background saving started by pid 1161
1161:1159:C 03 Jun 2022 13:27:30.850 * DB saved on disk
1161:1159:C 03 Jun 2022 13:27:30.850 * RDB: 0 MB of memory used by copy-on-write
1152:1159:S 03 Jun 2022 13:27:30.868 * Background saving terminated with success
1152:1159:S 03 Jun 2022 13:27:30.869 * Synchronization with replica 192.168.122.70:6379 succeeded
1152:1159:S 03 Jun 2022 13:27:31.073 * Connecting to MASTER 192.168.122.70:6379
1152:1159:S 03 Jun 2022 13:27:31.073 * MASTER <-> REPLICA sync started
1152:1159:S 03 Jun 2022 13:27:31.074 * Non blocking connect for SYNC fired the event.
1152:1159:S 03 Jun 2022 13:27:31.074 * Master replied to PING, replication can continue...
1152:1159:S 03 Jun 2022 13:27:31.075 * Partial resynchronization not possible (no cached master)
1152:1159:S 03 Jun 2022 13:27:31.077 * Full resync from master: eb21b52f21c58eb3382c9db1bb8d33c91a4f480d:4738
1152:1159:S 03 Jun 2022 13:27:31.078 * Discarding previously cached master state.
1152:1159:S 03 Jun 2022 13:27:31.142 * MASTER <-> REPLICA sync: receiving 629 bytes from master to disk
1152:1159:S 03 Jun 2022 13:27:31.142 * MASTER <-> REPLICA sync: Loading DB in memory
1152:1159:S 03 Jun 2022 13:27:31.146 * Loading RDB produced by version 6.2.2
1152:1159:S 03 Jun 2022 13:27:31.146 * RDB age 0 seconds
1152:1159:S 03 Jun 2022 13:27:31.146 * RDB memory usage when created 129.51 Mb
1152:1159:S 03 Jun 2022 13:27:31.146 # Done loading RDB, keys loaded: 8, keys expired: 0.
1152:1159:S 03 Jun 2022 13:27:31.146 * MASTER <-> REPLICA sync: Finished with success

```

Issue 2:
- As in Issue 1, before test, delete the `.rdb` file
- Create 9 keys, both instances should have them
- Delete 1 key `key-1`
- Shut Down VM1 abruptly. I did that in the Virtual Machine Manager with `Shut Down` -> `Force Off`
- Delete 2 more keys `key-2` and `key-3`. Confirm there are 6 keys left.
- After around 5 seconds, turn VM1 back on. After a few seconds, `key-1` reappears. `key-2` and `key-3` do not.
- This way, I have also managed to have the servers out-of-sync, where one instance had more keys than the other.

VM1:
```
429:429:C 03 Jun 2022 13:20:13.249 * Notice: "active-replica yes" implies "replica-read-only no"
429:429:C 03 Jun 2022 13:20:13.249 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
468:429:C 03 Jun 2022 13:20:13.262 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
468:429:C 03 Jun 2022 13:20:13.262 # KeyDB version=6.2.2, bits=64, commit=00000000, modified=0, pid=468, just started
468:429:C 03 Jun 2022 13:20:13.262 # Configuration loaded
468:429:C 03 Jun 2022 13:20:13.262 # WARNING: server-threads is greater than this machine's core count.  Truncating to 1 threads
468:429:S 03 Jun 2022 13:20:13.263 * monotonic clock: POSIX clock_gettime
468:429:S 03 Jun 2022 13:20:13.274 # Server initialized
468:429:S 03 Jun 2022 13:20:13.274 * Loading RDB produced by version 6.2.2
468:429:S 03 Jun 2022 13:20:13.274 * RDB age 177 seconds
468:429:S 03 Jun 2022 13:20:13.274 * RDB memory usage when created 129.51 Mb
468:429:S 03 Jun 2022 13:20:13.274 # Done loading RDB, keys loaded: 7, keys expired: 0.
468:429:S 03 Jun 2022 13:20:13.274 * DB loaded from disk: 0.000 seconds
468:429:S 03 Jun 2022 13:20:13.274 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
468:474:S 03 Jun 2022 13:20:13.281 * Thread 0 alive.
468:474:S 03 Jun 2022 13:20:13.281 * Connecting to MASTER 192.168.122.2:6379
468:474:S 03 Jun 2022 13:20:13.281 * MASTER <-> REPLICA sync started
468:474:S 03 Jun 2022 13:20:13.281 * Non blocking connect for SYNC fired the event.
468:474:S 03 Jun 2022 13:20:13.283 * Master replied to PING, replication can continue...
468:474:S 03 Jun 2022 13:20:13.283 * Partial resynchronization not possible (no cached master)
468:474:S 03 Jun 2022 13:20:13.285 * Full resync from master: 26f81784b08484d742affad5e2ffd8f6c5388929:35469
468:474:S 03 Jun 2022 13:20:13.285 * Discarding previously cached master state.
468:474:S 03 Jun 2022 13:20:13.321 * MASTER <-> REPLICA sync: receiving 519 bytes from master to disk
468:474:S 03 Jun 2022 13:20:13.321 * MASTER <-> REPLICA sync: Loading DB in memory
468:474:S 03 Jun 2022 13:20:13.327 * Loading RDB produced by version 6.2.2
468:474:S 03 Jun 2022 13:20:13.327 * RDB age 0 seconds
468:474:S 03 Jun 2022 13:20:13.327 * RDB memory usage when created 129.66 Mb
468:474:S 03 Jun 2022 13:20:13.327 # Done loading RDB, keys loaded: 6, keys expired: 0.
468:474:S 03 Jun 2022 13:20:13.327 * MASTER <-> REPLICA sync: Finished with success
468:474:S 03 Jun 2022 13:20:24.488 * Replica 192.168.122.2:6379 asks for synchronization
468:474:S 03 Jun 2022 13:20:24.488 * Full resync requested by replica 192.168.122.2:6379
468:474:S 03 Jun 2022 13:20:24.488 * Starting BGSAVE for SYNC with target: disk
468:474:S 03 Jun 2022 13:20:24.489 * Background saving started by pid 481
481:474:C 03 Jun 2022 13:20:24.505 * DB saved on disk
481:474:C 03 Jun 2022 13:20:24.508 * RDB: 0 MB of memory used by copy-on-write
468:474:S 03 Jun 2022 13:20:24.514 * Background saving terminated with success
468:474:S 03 Jun 2022 13:20:24.514 * Synchronization with replica 192.168.122.2:6379 succeeded
```

VM2:
```
1072:1078:S 03 Jun 2022 13:20:13.645 * Replica 192.168.122.70:6379 asks for synchronization
1072:1078:S 03 Jun 2022 13:20:13.645 * Full resync requested by replica 192.168.122.70:6379
1072:1078:S 03 Jun 2022 13:20:13.645 * Starting BGSAVE for SYNC with target: disk
1072:1078:S 03 Jun 2022 13:20:13.646 * Background saving started by pid 1123
1123:1078:C 03 Jun 2022 13:20:13.655 * DB saved on disk
1123:1078:C 03 Jun 2022 13:20:13.656 * RDB: 0 MB of memory used by copy-on-write
1072:1078:S 03 Jun 2022 13:20:13.682 * Background saving terminated with success
1072:1078:S 03 Jun 2022 13:20:13.682 * Synchronization with replica 192.168.122.70:6379 succeeded
1072:1078:S 03 Jun 2022 13:20:24.046 # Connection with master lost.
1072:1078:S 03 Jun 2022 13:20:24.046 * Caching the disconnected master state.
1072:1078:S 03 Jun 2022 13:20:24.585 * Connecting to MASTER 192.168.122.70:6379
1072:1078:S 03 Jun 2022 13:20:24.585 * MASTER <-> REPLICA sync started
1072:1078:S 03 Jun 2022 13:20:24.586 * Non blocking connect for SYNC fired the event.
1072:1078:S 03 Jun 2022 13:20:24.587 * Master replied to PING, replication can continue...
1072:1078:S 03 Jun 2022 13:20:24.587 * Partial resynchronization not possible (no cached master)
1072:1078:S 03 Jun 2022 13:20:24.589 * Full resync from master: c20eb3c4a8e237aa91931203757cfd67e19b0a53:19166
1072:1078:S 03 Jun 2022 13:20:24.589 * Discarding previously cached master state.
1072:1078:S 03 Jun 2022 13:20:24.614 * MASTER <-> REPLICA sync: receiving 573 bytes from master to disk
1072:1078:S 03 Jun 2022 13:20:24.614 * MASTER <-> REPLICA sync: Loading DB in memory
1072:1078:S 03 Jun 2022 13:20:24.620 * Loading RDB produced by version 6.2.2
1072:1078:S 03 Jun 2022 13:20:24.620 * RDB age 0 seconds
1072:1078:S 03 Jun 2022 13:20:24.620 * RDB memory usage when created 129.53 Mb
1072:1078:S 03 Jun 2022 13:20:24.620 # Done loading RDB, keys loaded: 7, keys expired: 0.
1072:1078:S 03 Jun 2022 13:20:24.620 * MASTER <-> REPLICA sync: Finished with success
1072:1078:S 03 Jun 2022 13:20:25.070 # Connection with replica client id #3782 lost.
```
**To reproduce**

My architecture is as follows: two Debian 11 VMs. Every VM has a keepalived, HAProxy and KeyDB instance, pretty much as described in this article: https://faun.pub/failover-redis-like-cluster-from-two-masters-with-keydb-9ab8e806b66c. Keepalived is on version 2.1.5, HAProxy is on 2.2.9-2+deb11u3 and KeyDB on 6.2.2. The VMs have 1 CPU core and 2GM RAM each.

Please find my config files in this repository: https://github.com/Mall0c/keydb-multi-master-issues

**Expected behavior**

A state of the servers in which the instances have the correct values.

**Additional information**

`vm.overcommit_memory = 1` is set in /etc/sysctl.conf, as suggested in the documentation.

Thanks,
Richard

**Comment by solracsf** [comment] 2022-06-06 07:19
Hi, can this be reproduced with v6.3.1 ?

**Comment by Mall0c** [comment] 2022-06-07 07:52
I've had similar issues with 6.3.1. Can this be due to the OS I am testing it on? https://docs.keydb.dev/docs/ppa-deb/ does not list Debian bullseye

**Comment by Namoshek** [comment] 2022-06-07 17:35
I've noticed the same thing before, but couldn't reliably reproduce it so far. We are using RDB + AOF at the same time, though I can see the active replication being an issue with both, RDB and AOF, individually as well.

In case of the AOF, so far my best guess is that it has to do with timing (of the shutdown and restart) and potentially the state of the AOF as well. I'm not deep enough into the matter, but my theory is that after the AOF has been rewritten to have the minimal set of instructions to reproduce the current state, it might not contain delete statements anymore (i.e. `SET` + `DEL` cancel each other out, at least in my understanding). Which means that if another node, which was offline during the `DEL` command, comes up again, it will reintroduce the key to the node(s) which were online all the time. And in fact, this could be exactly what is happening in case of the RDB solution as well.

By the way, we are not using TTLs on the keys. The application(s) in which we encountered said issue are using KeyDB for actual persistence as alternative to an SQL server (purely for performance reasons so far). So this really is a bit of a problem, since we somehow lost trust in our data already...

**Comment by benschermel** [comment] 2022-06-09 02:07
I have created issue #447 to request support for this. You may want to consider using EXPIREs as DEL does not yet have tombstone support. We are currently working on updating our documentation for this

**Comment by benschermel** [comment] 2022-06-09 02:21
closing issue with reference to #447. If the request does not match what you are seeing please let me know

**Closed by benschermel** 2022-06-09 02:21 UTC

**Comment by gappymate** [comment] 2022-08-31 08:24
I am having the same issue. Is there anything new to this? Would be great if there is any new information.

Kind regards,
Albert
albert1.cornelius+github@gmail.com
