### ISSUE TITLE
[CRASH] KeyDB with Flash crashes after restarts

### ISSUE THREAD

**Issue by skolosov-snap** [Snapchat/KeyDB#598] opened 2023-03-09 17:40 UTC
**Crash report**

I believe I've seen this Assert Failure before, but I believe it should be fixed in my version already.

Paste the complete crash log between the quotes below. Please include a few lines from the log preceding the crash report to provide some context.

```
2023-03-09_17:34:06: INFO: Found only one Local SSD device. No RAID needed. Formatting and mounting /dev/nvme0n1...
2023-03-09_17:34:06: INFO: Device /dev/nvme0n1 already formatted with  TYPE="ext3". Skipping...
2023-03-09_17:34:06: INFO: Creating mounting path if needed: /mnt/data
2023-03-09_17:34:06: INFO: Mounting /dev/nvme0n1 to /mnt/data...
2023-03-09_17:34:07: INFO: Clearing all data in /mnt/data/keydb-data and recreating data folder...
Program started at: 2023-03-09 17:34:07.119190135 +0000 UTC m=+0.011334152
REDIS_VERSION=6.2.6
I0309 17:34:07.120072      26 redisnode.go:86] Delaying server start for 30s...
I0309 17:34:37.121180      26 node.go:242] Clearing '/redis-data' folder...
I0309 17:34:37.121234      26 node.go:256] Removing /redis-data/node.conf
I0309 17:34:37.121295      26 node.go:256] Removing /redis-data/temp--948994069.37.rdb
I0309 17:34:37.121450      26 redisnode.go:366] Trying test connection to 10.110.44.202:17379 till 2023-03-09 17:34:47.121434929 +0000 UTC m=+40.013578933
I0309 17:34:37.121503      26 redisnode.go:323] Listening on http://0.0.0.0:8088
I0309 17:34:37.121647      26 redis.go:130] Loaded Root CA certs from /credentials/root_cert.pem.
I0309 17:34:37.121846      26 redis.go:150] Loaded client cert from files (cerPath=/credentials/rsa.certs.pem, keyPath=/credentials/rsa.key.pem).
E0309 17:34:37.121980      26 redisnode.go:389] Can't create client to 10.110.44.202:17379: dial tcp 10.110.44.202:17379: connect: connection refused
I0309 17:34:37.121996      26 redisnode.go:374] Retrying ping to 10.110.44.202:17379 in 0.5 seconds
37:37:C 09 Mar 2023 17:34:37.132 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
37:37:C 09 Mar 2023 17:34:37.132 # KeyDB version=255.255.255, bits=64, commit=8fc48125, modified=1, pid=37, just started
37:37:C 09 Mar 2023 17:34:37.132 # Configuration loaded
37:37:C 09 Mar 2023 17:34:37.132 * Initializing FLASH storage provider (this may take a long time)
37:37:M 09 Mar 2023 17:34:37.344 * monotonic clock: POSIX clock_gettime
37:37:M 09 Mar 2023 17:34:37.344 * No cluster configuration found, I'm c84590c53f6a7a91965257eead7709ef68c31595
37:37:M 09 Mar 2023 17:34:37.347 * Running mode=cluster, port=17379.
37:37:M 09 Mar 2023 17:34:37.347 # Server initialized
37:37:M 09 Mar 2023 17:34:37.348 * Module 'statsd' loaded from /usr/local/lib/modstatsd.so
37:37:M 09 Mar 2023 17:34:37.349 * Loading the RDB even though we have a storage provider because the database is empty
37:37:M 09 Mar 2023 17:34:37.349 # Warning: server-threads is set to 6.  This is above the maximum recommend value of 4, please ensure you've verified this is actually faster on your machine.
37:77:M 09 Mar 2023 17:34:37.349 * Thread 0 alive.
37:78:M 09 Mar 2023 17:34:37.349 * Thread 1 alive.
37:79:M 09 Mar 2023 17:34:37.349 * Thread 2 alive.
37:80:M 09 Mar 2023 17:34:37.349 * Thread 3 alive.
37:81:M 09 Mar 2023 17:34:37.349 * Thread 4 alive.
37:82:M 09 Mar 2023 17:34:37.349 * Thread 5 alive.
I0309 17:34:37.623070      26 redisnode.go:366] Trying test connection to 10.110.44.202:17379 till 2023-03-09 17:34:47.121434929 +0000 UTC m=+40.013578933
I0309 17:34:37.623268      26 redis.go:130] Loaded Root CA certs from /credentials/root_cert.pem.
I0309 17:34:37.623388      26 redis.go:150] Loaded client cert from files (cerPath=/credentials/rsa.certs.pem, keyPath=/credentials/rsa.key.pem).
37:79:M 09 Mar 2023 17:34:37.628 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
I0309 17:34:37.628264      26 redisnode.go:401] Successfully pinged local server at 10.110.44.202:17379.
I0309 17:34:38.135711      26 redisnode.go:209] REDIS Node addresses:10.110.44.180:17379
I0309 17:34:38.135726      26 redisnode.go:209] REDIS Node addresses:10.110.44.226:17379
I0309 17:34:38.135730      26 redisnode.go:209] REDIS Node addresses:10.110.45.100:17379
I0309 17:34:38.135733      26 redisnode.go:209] REDIS Node addresses:10.110.45.101:17379
I0309 17:34:38.135736      26 redisnode.go:209] REDIS Node addresses:10.110.45.102:17379
I0309 17:34:38.135739      26 redisnode.go:209] REDIS Node addresses:10.110.45.15:17379
I0309 17:34:38.135743      26 redisnode.go:209] REDIS Node addresses:10.110.45.23:17379
I0309 17:34:38.135747      26 redisnode.go:209] REDIS Node addresses:10.110.45.26:17379
I0309 17:34:38.135849      26 redis.go:130] Loaded Root CA certs from /credentials/root_cert.pem.
I0309 17:34:38.135943      26 redis.go:150] Loaded client cert from files (cerPath=/credentials/rsa.certs.pem, keyPath=/credentials/rsa.key.pem).
I0309 17:34:38.172422      26 redisnode.go:185] Attaching node to 10.110.44.202:17379 cluster
I0309 17:34:38.172436      26 admin.go:155] Attaching node 10.110.44.202:17379 to cluster.
37:77:M 09 Mar 2023 17:34:38.177 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
I0309 17:34:38.178379      26 admin.go:181] node 10.110.44.202:17379 attached properly
I0309 17:34:38.178900      26 redisnode.go:198] RedisNode: Running properly
I0309 17:34:38.178919      26 redisnode.go:107] Awaiting stop signal
37:77:M 09 Mar 2023 17:34:38.194 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
37:77:M 09 Mar 2023 17:34:38.194 # IP address for this node updated to 10.110.44.202
37:77:M 09 Mar 2023 17:34:38.196 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
37:77:M 09 Mar 2023 17:34:38.224 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
37:77:M 09 Mar 2023 17:34:38.234 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
37:77:M 09 Mar 2023 17:34:38.268 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
37:77:M 09 Mar 2023 17:34:38.269 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
37:77:M 09 Mar 2023 17:34:38.269 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
37:77:M 09 Mar 2023 17:34:38.270 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
37:77:M 09 Mar 2023 17:34:39.380 # Cluster state changed: ok
I0309 17:34:43.076919      26 redis.go:130] Loaded Root CA certs from /credentials/root_cert.pem.
I0309 17:34:43.077072      26 redis.go:150] Loaded client cert from files (cerPath=/credentials/rsa.certs.pem, keyPath=/credentials/rsa.key.pem).
I0309 17:34:43.077161      26 redis.go:130] Loaded Root CA certs from /credentials/root_cert.pem.
I0309 17:34:43.077296      26 redis.go:150] Loaded client cert from files (cerPath=/credentials/rsa.certs.pem, keyPath=/credentials/rsa.key.pem).
I0309 17:34:43.080277      26 redisnode.go:309] Liveness probe ok
37:78:M 09 Mar 2023 17:34:43.081 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
37:77:M 09 Mar 2023 17:34:43.083 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
I0309 17:34:43.083329      26 redisnode.go:298] Readiness probe ok
I0309 17:34:43.083479      26 redis.go:130] Loaded Root CA certs from /credentials/root_cert.pem.
I0309 17:34:43.083572      26 redis.go:150] Loaded client cert from files (cerPath=/credentials/rsa.certs.pem, keyPath=/credentials/rsa.key.pem).
I0309 17:34:43.086523      26 redisnode.go:309] Liveness probe ok
37:81:M 09 Mar 2023 17:34:43.087 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
37:80:M 09 Mar 2023 17:34:43.161 * Audit Log: disabled for gke-nodepool@caching-infra-prod.iam.gserviceaccount.com
37:80:S 09 Mar 2023 17:34:43.214 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
37:80:S 09 Mar 2023 17:34:43.214 * Connecting to MASTER 10.110.45.101:17379
37:80:S 09 Mar 2023 17:34:43.214 * MASTER <-> REPLICA sync started
37:80:S 09 Mar 2023 17:34:43.217 * Non blocking connect for SYNC fired the event.
37:80:S 09 Mar 2023 17:34:43.217 * Master replied to PING, replication can continue...
37:80:S 09 Mar 2023 17:34:43.218 * Trying a partial resynchronization (request b63cba05fb6ae0c37fbe2815fcb5b90f7a69f903:1).
37:80:S 09 Mar 2023 17:34:43.624 * Full resync from master: 0d71f5a39376c3806a5d85b66120b3679fe82c01:622789221
37:80:S 09 Mar 2023 17:34:43.624 * Discarding previously cached master state.
37:80:S 09 Mar 2023 17:34:43.630 * MASTER <-> REPLICA sync: Flushing old data
37:80:S 09 Mar 2023 17:34:45.313 * Fast sync complete
37:80:S 09 Mar 2023 17:34:45.313 * MASTER <-> REPLICA sync: Finished with success


=== KEYDB BUG REPORT START: Cut & paste starting from here ===
37:80:S 09 Mar 2023 17:34:45.334 # === ASSERTION FAILED ===
37:80:S 09 Mar 2023 17:34:45.334 # ==> db.cpp:2500 'fModified || g_pserver->db[0]->snapshot_depth() > 0 || noModify' is not true

------ STACK TRACE ------

Backtrace:
keydb-server 0.0.0.0:17379 [cluster](slotToKeyUpdateKeyCore(char const*, unsigned long, int, int)+0x1f6) [0x55e4246c9f56]
keydb-server 0.0.0.0:17379 [cluster](redisDbPersistentData::syncDelete(redisObject*)+0x1cf) [0x55e4246d309f]
keydb-server 0.0.0.0:17379 [cluster](delGenericCommand(client*, int)+0x8e) [0x55e4246d319e]
keydb-server 0.0.0.0:17379 [cluster](call(client*, int)+0xae) [0x55e4246ffdfe]
keydb-server 0.0.0.0:17379 [cluster](processCommand(client*, int)+0x71b) [0x55e424700d4b]
keydb-server 0.0.0.0:17379 [cluster](processCommandAndResetClient(client*, int)+0x6f) [0x55e4246e07cf]
keydb-server 0.0.0.0:17379 [cluster](processInputBuffer(client*, bool, int)+0x1ec) [0x55e4246e45dc]
keydb-server 0.0.0.0:17379 [cluster](processClients()+0x118) [0x55e4246e4798]
keydb-server 0.0.0.0:17379 [cluster](+0x25bdee) [0x55e4246f8dee]
keydb-server 0.0.0.0:17379 [cluster](beforeSleep(aeEventLoop*)+0x15a) [0x55e42470c38a]
keydb-server 0.0.0.0:17379 [cluster](aeProcessEvents+0x3d0) [0x55e424710690]
keydb-server 0.0.0.0:17379 [cluster](aeMain+0x3a) [0x55e424710b7a]
keydb-server 0.0.0.0:17379 [cluster](workerThreadMain(void*)+0x88) [0x55e4246f8e98]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7efcf3507609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7efcf342a133]

------ INFO OUTPUT ------
# Server
redis_version:255.255.255
redis_git_sha1:8fc48125
redis_git_dirty:1
redis_build_id:e228dd6a36339e3f
redis_mode:cluster
os:Linux 5.10.147+ x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:9.4.0
process_id:37
process_supervised:no
run_id:f997b24815ff30fcaa37dd1055379b641ff13250
tcp_port:17379
server_time_usec:1678383285335481
uptime_in_seconds:8
uptime_in_days:0
hz:40
configured_hz:40
lru_clock:661685
executable:/data/keydb-server
config_file:/redis-conf/redis.conf
availability_zone:us-central1-c

# Clients
connected_clients:2
cluster_connections:16
maxclients:60000
client_recent_max_input_buffer:5743
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0
current_client_thread:3
thread_0_clients:0
thread_1_clients:0
thread_2_clients:0
thread_3_clients:2
thread_4_clients:0
thread_5_clients:0

# Memory
used_memory:2198013056
used_memory_human:2.05G
used_memory_rss:460451840
used_memory_rss_human:439.12M
used_memory_peak:2247098288
used_memory_peak_human:2.09G
used_memory_peak_perc:97.82%
used_memory_overhead:2190654975
used_memory_startup:25837960
used_memory_dataset:7358081
used_memory_dataset_perc:0.34%
allocator_allocated:421682856
allocator_active:426364928
allocator_resident:484495360
total_system_memory:33671958528
total_system_memory_human:31.36G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:8937614131
maxmemory_human:8.32G
maxmemory_policy:allkeys-lfu
allocator_frag_ratio:1.01
allocator_frag_bytes:4682072
allocator_rss_ratio:1.14
allocator_rss_bytes:58130432
rss_overhead_ratio:0.95
rss_overhead_bytes:-24043520
mem_fragmentation_ratio:1.10
mem_fragmentation_bytes:41987784
mem_not_counted_for_evict:2000000000
mem_replication_backlog:2147483648
mem_clients_slaves:0
mem_clients_normal:46735
mem_aof_buffer:0
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0
storage_provider:flash
flash_memory:0

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:50
rdb_bgsave_in_progress:0
rdb_last_save_time:1678383277
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:6
total_commands_processed:62
instantaneous_ops_per_sec:0
total_net_input_bytes:82214
total_net_output_bytes:9421
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:17
total_writes_processed:8
instantaneous_lock_contention:1
avg_lock_contention:0.890625
storage_provider_read_hits:0
storage_provider_read_misses:50

# Replication
role:slave
master_global_link_status:up
connected_masters:1
master_host:10.110.45.101
master_port:17379
master_link_status:up
master_last_io_seconds_ago:0
master_sync_in_progress:0
slave_read_repl_offset:622871141
slave_repl_offset:622860572
slave_priority:100
slave_read_only:1
replica_announced:1
connected_slaves:0
master_failover_state:no-failover
master_replid:0d71f5a39376c3806a5d85b66120b3679fe82c01
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:622860572
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:2000000000
repl_backlog_first_byte_offset:622789222
repl_backlog_histlen:71351

# CPU
used_cpu_sys:1.462714
used_cpu_user:1.969406
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
server_threads:6
long_lock_waits:0
used_cpu_sys_main_thread:0.421866
used_cpu_user_main_thread:1.166159

# Modules
module:name=statsd,ver=1,api=1,filters=0,usedby=[],using=[],options=[]

# Commandstats
cmdstat_set:calls=50,usec=184,usec_per_call=3.68,rejected_calls=0,failed_calls=0
cmdstat_client:calls=1,usec=6,usec_per_call=6.00,rejected_calls=0,failed_calls=0
cmdstat_ping:calls=1,usec=1,usec_per_call=1.00,rejected_calls=0,failed_calls=0
cmdstat_dbsize:calls=1,usec=1,usec_per_call=1.00,rejected_calls=0,failed_calls=0
cmdstat_select:calls=1,usec=1,usec_per_call=1.00,rejected_calls=0,failed_calls=0
cmdstat_config:calls=1,usec=74,usec_per_call=74.00,rejected_calls=0,failed_calls=0
cmdstat_cluster:calls=5,usec=442,usec_per_call=88.40,rejected_calls=0,failed_calls=0
cmdstat_info:calls=2,usec=123,usec_per_call=61.50,rejected_calls=0,failed_calls=0

# Errorstats

# Cluster
cluster_enabled:1

# Keyspace
db0:keys=431980,expires=96,avg_ttl=40015634,cached_keys=96

# KeyDB
mvcc_depth:0

------ CLIENT LIST OUTPUT ------
id=14 addr=10.136.137.163:42740 laddr=10.110.44.202:17379 fd=74 name= age=2 idle=2 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20512 events=r cmd=cluster user=default redir=-1
id=16 addr=10.110.45.101:17379 laddr=10.110.44.202:40659 fd=75 name= age=0 idle=0 flags=M db=0 sub=0 psub=0 multi=-1 qbuf=802 qbuf-free=40152 argv-mem=5630 obl=0 oll=0 omem=0 tot-mem=67454 events=r cmd=del user=(superuser) redir=-1

------ CURRENT CLIENT INFO ------
id=16 addr=10.110.45.101:17379 laddr=10.110.44.202:40659 fd=75 name= age=0 idle=0 flags=M db=0 sub=0 psub=0 multi=-1 qbuf=802 qbuf-free=40152 argv-mem=5630 obl=0 oll=0 omem=0 tot-mem=67454 events=r cmd=del user=(superuser) redir=-1
argv[0]: 'DEL'
argv[1]: 'test'
argv[2]: 'test'
argv[3]: 'test'
argv[4]: 'test'
argv[5]: 'test'
argv[6]: 'test'
argv[7]: 'test'
argv[8]: 'test'
argv[9]: 'test'
argv[10]: 'test'
argv[11]: 'test'
argv[12]: 'test'
argv[13]: 'test'
argv[14]: 'test'
argv[15]: 'test'
argv[16]: 'test'
argv[17]: 'test'
argv[18]: 'test'
argv[19]: 'test'
argv[20]: 'test'
argv[21]: 'test'
argv[22]: 'test'
argv[23]: 'test'
argv[24]: 'test'
argv[25]: 'test'
argv[26]: 'test'
argv[27]: 'test'
argv[28]: 'test'
argv[29]: 'test'
argv[30]: 'test'
argv[31]: 'test'
argv[32]: 'test'
argv[33]: 'test'
argv[34]: 'test'
argv[35]: 'test'
argv[36]: 'test'
argv[37]: 'test'
argv[38]: 'test'
argv[39]: 'test'
argv[40]: 'test'
argv[41]: 'test'
argv[42]: 'test'
argv[43]: 'test'
argv[44]: 'test'
argv[45]: 'test'
argv[46]: 'test'
argv[47]: 'test'

------ MODULES INFO OUTPUT ------

------ FAST MEMORY TEST ------
37:80:S 09 Mar 2023 17:34:45.335 # main thread terminated
37:80:S 09 Mar 2023 17:34:45.335 # Bio thread for job type #0 terminated
37:80:S 09 Mar 2023 17:34:45.336 # Bio thread for job type #1 terminated
37:80:S 09 Mar 2023 17:34:45.336 # Bio thread for job type #2 terminated

Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

=== KEYDB BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           https://github.com/JohnSully/KeyDB/issues

  Suspect RAM error? Use keydb-server --test-memory to verify it.


```

**Aditional information**

1. OS distribution and version
2. Steps to reproduce (if any)

**Comment by msotheeswaran** [comment] 2023-03-09 18:39
duplicate of #574

**Closed by msotheeswaran** 2023-03-09 18:39 UTC
