### ISSUE TITLE
[BUG] KeyDB becomes unresponsive with larget number of socket connections

### ISSUE THREAD

**Issue by KeithDonoghue-Blis** [Snapchat/KeyDB#596] opened 2023-03-08 21:07 UTC
**Describe the bug**

After a long running period of time (weeks) KeyDB becomes unresponsive with a large number of redundant 'socket' FDs. These persist even after all connections have ended.

**To reproduce**

We have a set of c++ applications connecting over the network to a remote KeyDB instance. Periodically, after a period of days or weeks
we notice an increase in clients connected as reported by INFO CLIENTS without an increase in network connections. These clients do not close.  
`lsof -i | grep sock`

```

keydb-ser  6280                   keydb *626u     sock      0,9      0t0 82736687 protocol: TCP
keydb-ser  6280                   keydb *627u     sock      0,9      0t0 82738521 protocol: TCP
keydb-ser  6280                   keydb *628u     sock      0,9      0t0 82734728 protocol: TCP
keydb-ser  6280                   keydb *629u     sock      0,9      0t0 82735872 protocol: TCP
keydb-ser  6280                   keydb *630u     sock      0,9      0t0 82738533 protocol: TCP
keydb-ser  6280                   keydb *631u     sock      0,9      0t0 82737599 protocol: TCP
keydb-ser  6280                   keydb *632u     sock      0,9      0t0 82734746 protocol: TCP
keydb-ser  6280                   keydb *633u     sock      0,9      0t0 82740500 protocol: TCP
keydb-ser  6280                   keydb *634u     sock      0,9      0t0 82737959 protocol: TCP
keydb-ser  6280                   keydb *635u     sock      0,9      0t0 82737961 protocol: TCP
keydb-ser  6280                   keydb *636u     sock      0,9      0t0 82739805 protocol: TCP
keydb-ser  6280                   keydb *637u     sock      0,9      0t0 82740503 protocol: TCP
keydb-ser  6280                   keydb *638u     sock      0,9      0t0 82740510 protocol: TCP
keydb-ser  6280                   keydb *639u     sock      0,9      0t0 82739809 protocol: TCP
keydb-ser  6280                   keydb *640u     sock      0,9      0t0 82737970 protocol: TCP
keydb-ser  6280                   keydb *641u     sock      0,9      0t0 82737132 protocol: TCP
keydb-ser  6280                   keydb *642u     sock      0,9      0t0 82737978 protocol: TCP
keydb-ser  6280                   keydb *643u     sock      0,9      0t0 82740527 protocol: TCP
keydb-ser  6280                   keydb *644u     sock      0,9      0t0 82741704 protocol: TCP
keydb-ser  6280                   keydb *645u     sock      0,9      0t0 82740565 protocol: TCP
```

**Expected behavior**
KeyDB should remain responsive over the long term

**Additional information**

We are using verson 3.1 with jemalloc...
version string: KeyDB server v=6.3.1 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=3fe315c8f17a49e

**Comment by msotheeswaran** [comment] 2023-03-09 18:41
duplicate of #465

**Closed by msotheeswaran** 2023-03-09 18:41 UTC
